/* Extra catalogue wave 17 — quality infrastructure: management-system,
 * conformity-assessment and laboratory-medicine adoptions (IS/ISO series).
 * These rows back the certification guide and the "which scheme applies"
 * questions with internationally aligned designations.
 *
 * Note: `buildBlock` marks a row mandatory only when it carries an explicit
 * scheme flag; every row here is voluntary, so the block simply supplies the
 * scheme label shown in the catalogue. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const QMS: Block = {
  category: "services",
  voluntaryScheme: "Management System Certification",
  rows: [
    ["IS/ISO 9000:2015", "Quality Management Systems — Fundamentals and Vocabulary", "Core concepts, principles and terms used across the ISO 9000 family."],
    ["IS/ISO 9004:2018", "Quality Management — Quality of an Organization — Guidance to Achieve Sustained Success", "Maturity-based guidance for extending a QMS beyond conformity."],
    ["IS/ISO 10001:2018", "Quality Management — Customer Satisfaction — Guidelines for Codes of Conduct", "Designing and implementing promises made to customers."],
    ["IS/ISO 10002:2018", "Quality Management — Customer Satisfaction — Guidelines for Complaints Handling", "Complaint receipt, tracking, escalation and remedy processes."],
    ["IS/ISO 10003:2018", "Quality Management — Customer Satisfaction — Guidelines for External Dispute Resolution", "Designing fair and accessible out-of-court dispute resolution."],
    ["IS/ISO 10004:2018", "Quality Management — Customer Satisfaction — Guidelines for Monitoring and Measuring", "Metrics and sampling for tracking customer satisfaction over time."],
    ["IS/ISO 10005:2018", "Quality Management — Guidelines for Quality Plans", "When a quality plan is needed and what it must contain."],
    ["IS/ISO 10006:2017", "Quality Management — Guidelines for Quality Management in Projects", "Quality practices across project life-cycle processes."],
    ["IS/ISO 10007:2017", "Quality Management — Guidelines for Configuration Management", "Change control, status accounting and configuration audits."],
    ["IS/ISO 10008:2013", "Quality Management — Customer Satisfaction — Guidelines for Business-to-Consumer Electronic Commerce", "Trust, transaction integrity and redress in online retail."],
    ["IS/ISO 10012:2003", "Measurement Management Systems — Requirements for Measurement Processes and Measuring Equipment", "Metrological confirmation of measuring equipment."],
    ["IS/ISO 10013:2021", "Quality Management — Guidance for Documented Information", "Document hierarchy, control and retention."],
    ["IS/ISO 10014:2021", "Quality Management — Managing an Organization for Quality — Guidance for Achieving Financial Benefit", "Linking quality practice to financial and economic returns."],
    ["IS/ISO 10015:2019", "Quality Management — Guidelines for Competence Management and People Development", "Competence needs analysis, development and evaluation."],
    ["IS/ISO 10018:2020", "Quality Management — Guidelines for People Engagement", "Engagement factors that sustain improvement culture."],
    ["IS/ISO 10019:2005", "Guidelines for the Selection of Quality Management System Consultants", "Evaluating and appointing QMS consultants."],
    ["IS/ISO 90003:2018", "Software Engineering — Guidelines for the Application of ISO 9001 to Computer Software", "Applying QMS requirements to software products and services."],
    ["IS/ISO 19011:2018", "Guidelines for Auditing Management Systems", "Audit programme, auditor competence and audit conduct."],
    ["IS/ISO/IEC 17000:2020", "Conformity Assessment — Vocabulary and General Principles", "Definitions used across conformity-assessment standards."],
    ["IS/ISO/IEC 17007:2009", "Conformity Assessment — Guidance for Drafting Normative Documents", "Writing standards suited to conformity assessment."],
    ["IS/ISO/IEC 17011:2017", "Conformity Assessment — Requirements for Accreditation Bodies Accrediting Conformity Assessment Bodies", "Impartiality, competence and peer evaluation of accreditation bodies."],
    ["IS/ISO/IEC 17021-2:2016", "Conformity Assessment — Requirements for Bodies Providing Audit and Certification of Management Systems — Part 2: Competence Requirements for Auditing and Certifying Environmental Management Systems", "Competence criteria for EMS auditors."],
    ["IS/ISO/IEC 17021-3:2017", "Conformity Assessment — Requirements for Bodies Providing Audit and Certification of Management Systems — Part 3: Competence Requirements for Auditing and Certifying Quality Management Systems", "Competence criteria for QMS auditors."],
    ["IS/ISO/IEC 17029:2019", "Conformity Assessment — General Principles and Requirements for Validation and Verification Bodies", "Requirements for bodies issuing validation and verification statements."],
    ["IS/ISO/IEC 17030:2021", "Conformity Assessment — General Requirements for Third-Party Marks of Conformity", "Criteria for issuing marks that signal third-party conformity."],
    ["IS/ISO/IEC 17034:2016", "General Requirements for the Competence of Reference Material Producers", "Competence of producers of certified reference materials."],
    ["IS/ISO/IEC 17040:2005", "Conformity Assessment — General Requirements for Peer Assessment of Conformity Assessment Bodies and Accreditation Bodies", "Peer assessment agreements between accreditation bodies."],
    ["IS/ISO/IEC 17043:2010", "Conformity Assessment — General Requirements for Proficiency Testing", "Organising and evaluating inter-laboratory comparisons."],
    ["IS/ISO/IEC 17050-1:2004", "Conformity Assessment — Supplier's Declaration of Conformity — Part 1: General Requirements", "Issuing a supplier's declaration of conformity."],
    ["IS/ISO/IEC 17050-2:2004", "Conformity Assessment — Supplier's Declaration of Conformity — Part 2: Supporting Documentation", "Documentation retained behind a declaration of conformity."],
    ["IS/ISO/IEC 17065:2012", "Conformity Assessment — Requirements for Bodies Certifying Products, Processes and Services", "Impartiality, competence and certification process requirements.", "V", { related: ["IS/ISO/IEC 17067:2013", "IS/ISO 17025:2017"] }],
    ["IS/ISO/IEC 17067:2013", "Conformity Assessment — Fundamentals of Product Certification and Guidelines for Product Certification Schemes", "Design of product certification schemes, including Scheme-I style type testing."],
  ],
};

const ENVIRONMENT_AND_ENERGY: Block = {
  category: "services",
  voluntaryScheme: "Management System Certification",
  rows: [
    ["IS/ISO 14002-1:2019", "Environmental Management Systems — Guidelines for Using ISO 14001 to Address Environmental Aspects and Conditions within an Environmental Topic Area — Part 1: General", "Applying an EMS to a specific environmental topic area."],
    ["IS/ISO 14004:2016", "Environmental Management Systems — General Guidelines on Implementation", "Implementation guidance beyond the requirements of ISO 14001."],
    ["IS/ISO 14005:2019", "Environmental Management Systems — Guidelines for a Flexible Approach to Phased Implementation", "Stepwise EMS implementation for smaller organisations."],
    ["IS/ISO 14006:2020", "Environmental Management Systems — Guidelines for Incorporating Ecodesign", "Embedding ecodesign into environmental management."],
    ["IS/ISO 14009:2020", "Environmental Management Systems — Guidelines for Incorporating Material Circulation in Design and Development", "Design guidance to keep materials in circulation."],
    ["IS/ISO 14020:2022", "Environmental Labels and Declarations — General Principles", "Principles applying to all environmental labels and declarations."],
    ["IS/ISO 14021:2021", "Environmental Labels and Declarations — Self-Declared Environmental Claims (Type II Environmental Labelling)", "Substantiating self-declared environmental claims."],
    ["IS/ISO 14024:2018", "Environmental Labels and Declarations — Type I Environmental Labelling — Principles and Procedures", "Programme rules for third-party certified eco-labels."],
    ["IS/ISO 14025:2010", "Environmental Labels and Declarations — Type III Environmental Declarations — Principles and Procedures", "Sector rules for quantified environmental product declarations."],
    ["IS/ISO 14026:2017", "Environmental Labels and Declarations — Principles, Requirements and Guidelines for Communication of Footprint Information", "Communicating product footprint information consistently."],
    ["IS/ISO 14031:2021", "Environmental Management — Environmental Performance Evaluation — Guidelines", "Indicators for evaluating environmental performance."],
    ["IS/ISO 14040:2006", "Environmental Management — Life Cycle Assessment — Principles and Framework", "Principles and framework for life-cycle assessment."],
    ["IS/ISO 14044:2006", "Environmental Management — Life Cycle Assessment — Requirements and Guidelines", "Requirements and guidelines for conducting an LCA."],
    ["IS/ISO 14046:2014", "Environmental Management — Water Footprint — Principles, Requirements and Guidelines", "Water footprint assessment of products, processes and organisations."],
    ["IS/ISO 14050:2020", "Environmental Management — Vocabulary", "Standardised environmental management terminology."],
    ["IS/ISO 14063:2006", "Environmental Management — Environmental Communication — Guidelines and Examples", "Internal and external environmental communication."],
    ["IS/ISO 14064-2:2019", "Greenhouse Gases — Part 2: Specification with Guidance at the Project Level for Quantification, Monitoring and Reporting of Greenhouse Gas Emission Reductions or Removal Enhancements", "Quantifying GHG project reductions and removals."],
    ["IS/ISO 14064-3:2019", "Greenhouse Gases — Part 3: Specification with Guidance for the Verification and Validation of Greenhouse Gas Statements", "Verifying and validating GHG statements."],
    ["IS/ISO 14065:2020", "General Principles and Requirements for Bodies Validating and Verifying Environmental Information", "Requirements for GHG validation and verification bodies."],
    ["IS/ISO 14066:2011", "Greenhouse Gases — Competence Requirements for Greenhouse Gas Validation Teams and Verification Teams", "Competence criteria for GHG teams."],
    ["IS/ISO 14067:2018", "Greenhouse Gases — Carbon Footprint of Products — Requirements and Guidelines for Quantification", "Product carbon footprint quantification."],
    ["IS/ISO 14090:2019", "Adaptation to Climate Change — Principles, Requirements and Guidelines", "Adaptation planning and reporting for organisations."],
    ["IS/ISO 14091:2021", "Adaptation to Climate Change — Guidelines on Vulnerability, Impacts and Risk Assessment", "Assessing climate vulnerability, impacts and risk."],
    ["IS/ISO 14097:2021", "Framework Including Principles and Requirements for Assessing and Reporting Investments and Financing Activities Related to Climate Change", "Climate-related assessment of investments and finance."],
    ["IS/ISO 14068-1:2023", "Climate Change Management — Transition to Net Zero — Part 1: Carbon Neutrality", "Requirements for carbon neutrality claims and their substantiation."],
    ["IS/ISO 50002:2014", "Energy Audits — Requirements with Guidance for Use", "Planning, conducting and reporting an energy audit."],
    ["IS/ISO 50003:2021", "Energy Management Systems — Requirements for Bodies Providing Audit and Certification of Energy Management Systems", "Competence and process requirements for EnMS certification."],
    ["IS/ISO 50004:2020", "Energy Management Systems — Guidance for the Implementation, Maintenance and Improvement of an Energy Management System", "Practical EnMS implementation guidance."],
    ["IS/ISO 50006:2014", "Energy Management Systems — Measuring Energy Performance Using Energy Baselines and Energy Performance Indicators", "Establishing baselines and performance indicators."],
    ["IS/ISO 50015:2014", "Energy Management Systems — Measurement and Verification of Energy Performance of Organizations — General Principles and Guidance", "Measurement and verification of energy performance."],
    ["IS/ISO 20121:2012", "Event Sustainability Management Systems — Requirements with Guidance for Use", "Sustainable event management and legacy planning."],
    ["IS/ISO 26000:2010", "Guidance on Social Responsibility", "Social responsibility concepts, core subjects and integration guidance."],
    ["IS/ISO 41001:2018", "Facility Management — Management Systems — Requirements with Guidance for Use", "Facilities management system requirements."],
    ["IS/ISO 41012:2017", "Facility Management — Guidance on Strategic Sourcing and the Development of Agreements", "Sourcing strategy and FM agreement development."],
    ["IS/ISO 55001:2014", "Asset Management — Management Systems — Requirements", "Asset management system requirements across the asset life cycle."],
    ["IS/ISO 55002:2018", "Asset Management — Management Systems — Guidelines for the Application of ISO 55001", "Applying asset management system requirements."],
    ["IS/ISO 56000:2020", "Innovation Management — Fundamentals and Vocabulary", "Core terminology for innovation management."],
    ["IS/ISO 56002:2019", "Innovation Management — Innovation Management System — Guidance", "Guidance for setting up an innovation management system."],
    ["IS/ISO 21401:2018", "Tourism and Related Services — Sustainability Management System for Accommodation Establishments — Requirements", "Sustainability requirements for accommodation providers."],
    ["IS/ISO 39001:2012", "Road Traffic Safety (RTS) Management Systems — Requirements with Guidance for Use", "Road safety management system requirements."],
    ["IS/ISO 30301:2019", "Information and Documentation — Management Systems for Records — Requirements", "Records management system requirements."],
    ["IS/ISO 30414:2018", "Human Resource Management — Guidelines for Internal and External Human Capital Reporting", "Consistent human capital reporting metrics."],
    ["IS/ISO 31010:2019", "Risk Management — Risk Assessment Techniques", "Selecting and applying risk assessment techniques."],
    ["IS/ISO 37001:2016", "Anti-Bribery Management Systems — Requirements with Guidance for Use", "Anti-bribery controls, due diligence and governance."],
    ["IS/ISO 37301:2021", "Compliance Management Systems — Requirements with Guidance for Use", "Compliance obligations, controls and culture."],
    ["IS/ISO 45003:2021", "Occupational Health and Safety Management — Psychological Health and Safety at Work — Guidelines for Managing Psychosocial Risks", "Identifying and managing psychosocial risks at work."],
  ],
};

const INFORMATION_AND_SERVICE: Block = {
  category: "services",
  voluntaryScheme: "Management System Certification",
  rows: [
    ["IS/ISO/IEC 27002:2022", "Information Security, Cybersecurity and Privacy Protection — Information Security Controls", "Implementation guidance for information security controls.", "V", { related: ["IS/ISO 27001:2022"] }],
    ["IS/ISO/IEC 27003:2017", "Information Technology — Security Techniques — Information Security Management Systems — Guidance", "Implementation guidance for establishing an ISMS."],
    ["IS/ISO/IEC 27004:2016", "Information Technology — Security Techniques — Information Security Management — Monitoring, Measurement, Analysis and Evaluation", "Metrics for ISMS effectiveness."],
    ["IS/ISO/IEC 27005:2022", "Information Security, Cybersecurity and Privacy Protection — Guidance on Managing Information Security Risks", "Information security risk assessment and treatment."],
    ["IS/ISO/IEC 27017:2015", "Information Technology — Security Techniques — Code of Practice for Information Security Controls Based on ISO/IEC 27002 for Cloud Services", "Cloud-specific information security controls."],
    ["IS/ISO/IEC 27018:2019", "Information Technology — Security Techniques — Code of Practice for Protection of Personally Identifiable Information in Public Clouds", "Protecting personally identifiable information in cloud services."],
    ["IS/ISO/IEC 27032:2012", "Information Technology — Security Techniques — Guidelines for Cybersecurity", "Cybersecurity roles, collaboration and threat handling."],
    ["IS/ISO/IEC 27033-1:2015", "Information Technology — Security Techniques — Network Security — Part 1: Overview and Concepts", "Network security architecture concepts and risk management."],
    ["IS/ISO/IEC 27033-2:2012", "Information Technology — Security Techniques — Network Security — Part 2: Guidelines for the Design and Implementation of Network Security", "Design and implementation guidance for network security."],
    ["IS/ISO/IEC 27033-3:2010", "Information Technology — Security Techniques — Network Security — Part 3: Reference Networking Scenarios", "Threats, design techniques and control issues for common scenarios."],
    ["IS/ISO/IEC 27034-1:2011", "Information Technology — Security Techniques — Application Security — Part 1: Overview and Concepts", "Application security concepts and framework."],
    ["IS/ISO/IEC 27035-1:2016", "Information Technology — Security Techniques — Information Security Incident Management — Part 1: Principles of Incident Management", "Incident management principles and phases."],
    ["IS/ISO/IEC 27035-2:2016", "Information Technology — Security Techniques — Information Security Incident Management — Part 2: Guidelines to Plan and Prepare for Incident Response", "Planning and preparing incident response capability."],
    ["IS/ISO/IEC 27036-1:2014", "Information Technology — Security Techniques — Information Security for Supplier Relationships — Part 1: Overview and Concepts", "Supplier relationship security concepts."],
    ["IS/ISO/IEC 27036-3:2013", "Information Technology — Security Techniques — Information Security for Supplier Relationships — Part 3: Guidelines for Information and Communication Technology Supply Chain Security", "ICT supply chain security guidance."],
    ["IS/ISO/IEC 27040:2015", "Information Technology — Security Techniques — Storage Security", "Storage security planning, design and operation."],
    ["IS/ISO/IEC 27701:2019", "Security Techniques — Extension to ISO/IEC 27001 and ISO/IEC 27002 for Privacy Information Management — Requirements and Guidelines", "Privacy information management system requirements."],
    ["IS/ISO/IEC 20000-1:2018", "Information Technology — Service Management — Part 1: Service Management System Requirements", "IT service management system requirements."],
    ["IS/ISO/IEC 20000-2:2019", "Information Technology — Service Management — Part 2: Guidance on the Application of Service Management Systems", "Applying service management system requirements."],
    ["IS/ISO/IEC 25010:2011", "Systems and Software Engineering — Systems and Software Quality Requirements and Evaluation (SQuaRE) — System and Software Quality Models", "Quality models for software products and systems."],
    ["IS/ISO/IEC 25040:2011", "Systems and Software Engineering — Systems and Software Quality Requirements and Evaluation (SQuaRE) — Evaluation Process", "Evaluation process for software quality requirements."],
    ["IS/ISO/IEC 12207:2017", "Systems and Software Engineering — Software Life Cycle Processes", "Software life-cycle processes for acquisition, development and operation."],
    ["IS/ISO 21001:2018", "Educational Organizations — Management Systems for Educational Organizations — Requirements with Guidance for Use", "Management system requirements for educational organisations."],
    ["IS/ISO 22313:2020", "Security and Resilience — Business Continuity Management Systems — Guidance on the Use of ISO 22301", "Guidance for applying business continuity requirements."],
    ["IS/ISO 18091:2019", "Quality Management Systems — Guidelines for the Application of ISO 9001 in Local Government", "Applying ISO 9001 across municipal services."],
    ["IS/ISO/IEC 17021-4:2016", "Conformity Assessment — Requirements for Bodies Providing Audit and Certification of Management Systems — Part 4: Competence Requirements for Auditing and Certifying Event Sustainability Management Systems", "Competence criteria for event sustainability auditors."],
  ],
};

const HEALTHCARE_AND_STERILIZATION: Block = {
  category: "services",
  voluntaryScheme: "Management System Certification",
  rows: [
    ["IS/ISO 15189:2022", "Medical Laboratories — Requirements for Quality and Competence", "Quality and competence requirements for medical testing laboratories."],
    ["IS/ISO 22716:2007", "Cosmetics — Good Manufacturing Practices (GMP) — Guidelines on Good Manufacturing Practices", "GMP guidance for cosmetic manufacture, storage and transport."],
    ["IS/ISO 14971:2019", "Medical Devices — Application of Risk Management to Medical Devices", "Risk management process for medical device life cycle."],
    ["IS/ISO 14155:2020", "Clinical Investigation of Medical Devices for Human Subjects — Good Clinical Practice", "Good clinical practice for medical device investigations."],
    ["IS/ISO 11135:2014", "Sterilization of Health-Care Products — Ethylene Oxide — Requirements for the Development, Validation and Routine Control of a Sterilization Process", "EO sterilisation development, validation and routine control."],
    ["IS/ISO 11137-1:2018", "Sterilization of Health Care Products — Radiation — Part 1: Requirements for Development, Validation and Routine Control of a Sterilization Process", "Radiation sterilisation requirements and dose control."],
    ["IS/ISO 11137-2:2013", "Sterilization of Health Care Products — Radiation — Part 2: Establishing the Sterilization Dose", "Methods for establishing the radiation sterilisation dose."],
    ["IS/ISO 11137-3:2017", "Sterilization of Health Care Products — Radiation — Part 3: Guidance on Dosimetric Aspects of Development, Validation and Routine Control", "Dosimetry guidance for radiation sterilisation."],
    ["IS/ISO 11138-1:2017", "Sterilization of Health Care Products — Biological Indicators — Part 1: General Requirements", "Biological indicator requirements for sterilisation processes."],
    ["IS/ISO 11138-2:2022", "Sterilization of Health Care Products — Biological Indicators — Part 2: Biological Indicators for Ethylene Oxide Sterilization Processes", "Biological indicators used to monitor EO sterilisation."],
    ["IS/ISO 11138-3:2017", "Sterilization of Health Care Products — Biological Indicators — Part 3: Biological Indicators for Moist Heat Sterilization Processes", "Biological indicators for moist heat processes."],
    ["IS/ISO 11737-1:2018", "Sterilization of Health Care Products — Microbiological Methods — Part 1: Determination of a Population of Microorganisms on Products", "Bioburden estimation for sterilisation validation."],
    ["IS/ISO 11737-2:2019", "Sterilization of Health Care Products — Microbiological Methods — Part 2: Tests of Sterility Performed in the Validation of a Sterilization Process", "Sterility testing during sterilisation validation."],
    ["IS/ISO 11607-1:2019", "Packaging for Terminally Sterilized Medical Devices — Part 1: Requirements for Materials, Sterile Barrier Systems and Packaging Systems", "Materials and sterile barrier system requirements."],
    ["IS/ISO 11607-2:2019", "Packaging for Terminally Sterilized Medical Devices — Part 2: Validation Requirements for Forming, Sealing and Assembly Processes", "Validation of forming, sealing and assembly processes."],
    ["IS/ISO 14644-1:2015", "Cleanrooms and Associated Controlled Environments — Part 1: Classification of Air Cleanliness by Particle Concentration", "Classification of air cleanliness classes ISO 1 to ISO 9."],
    ["IS/ISO 14644-2:2015", "Cleanrooms and Associated Controlled Environments — Part 2: Monitoring to Provide Evidence of Cleanroom Performance Related to Air Cleanliness by Particle Concentration", "Monitoring cleanroom performance for continued compliance."],
    ["IS/ISO 14644-3:2019", "Cleanrooms and Associated Controlled Environments — Part 3: Test Methods", "Test methods for cleanroom installation and performance."],
    ["IS/ISO 14644-4:2022", "Cleanrooms and Associated Controlled Environments — Part 4: Design, Construction and Start-Up", "Cleanroom design, construction and start-up requirements."],
    ["IS/ISO 14644-5:2004", "Cleanrooms and Associated Controlled Environments — Part 5: Operations", "Cleanroom operational practice and personnel discipline."],
    ["IS/ISO 14698-1:2003", "Cleanrooms and Associated Controlled Environments — Biocontamination Control — Part 1: General Principles and Methods", "Biocontamination control principles in cleanrooms."],
    ["IS/ISO 10993-1:2018", "Biological Evaluation of Medical Devices — Part 1: Evaluation and Testing within a Risk Management Process", "Framework for biological evaluation of medical devices."],
    ["IS/ISO 10993-3:2014", "Biological Evaluation of Medical Devices — Part 3: Tests for Genotoxicity, Carcinogenicity and Reproductive Toxicity", "Genotoxicity, carcinogenicity and reproductive toxicity testing."],
    ["IS/ISO 10993-4:2017", "Biological Evaluation of Medical Devices — Part 4: Selection of Tests for Interactions with Blood", "Blood interaction test selection for devices contacting blood."],
    ["IS/ISO 10993-5:2009", "Biological Evaluation of Medical Devices — Part 5: Tests for In Vitro Cytotoxicity", "In vitro cytotoxicity test methods."],
    ["IS/ISO 10993-6:2016", "Biological Evaluation of Medical Devices — Part 6: Tests for Local Effects after Implantation", "Local effects evaluation after implantation."],
    ["IS/ISO 10993-7:2008", "Biological Evaluation of Medical Devices — Part 7: Ethylene Oxide Sterilization Residuals", "EO and ECH residue limits and measurement."],
    ["IS/ISO 10993-9:2019", "Biological Evaluation of Medical Devices — Part 9: Framework for Identification and Quantification of Potential Degradation Products", "Degradation product identification and quantification."],
    ["IS/ISO 10993-10:2021", "Biological Evaluation of Medical Devices — Part 10: Tests for Skin Sensitization", "Skin sensitisation testing approaches."],
    ["IS/ISO 10993-11:2017", "Biological Evaluation of Medical Devices — Part 11: Tests for Systemic Toxicity", "Systemic toxicity test requirements."],
    ["IS/ISO 10993-12:2021", "Biological Evaluation of Medical Devices — Part 12: Sample Preparation and Reference Materials", "Sample preparation and reference material selection."],
    ["IS/ISO 10993-13:2010", "Biological Evaluation of Medical Devices — Part 13: Identification and Quantification of Degradation Products from Polymeric Medical Devices", "Degradation products from polymeric devices."],
    ["IS/ISO 10993-14:2001", "Biological Evaluation of Medical Devices — Part 14: Identification and Quantification of Degradation Products from Ceramics", "Degradation products from ceramic devices."],
    ["IS/ISO 10993-15:2019", "Biological Evaluation of Medical Devices — Part 15: Identification and Quantification of Degradation Products from Metals and Alloys", "Metal and alloy degradation product identification."],
    ["IS/ISO 10993-16:2017", "Biological Evaluation of Medical Devices — Part 16: Toxicokinetic Study Design for Degradation Products and Leachables", "Toxicokinetic study design for degradation products."],
    ["IS/ISO 10993-17:2023", "Biological Evaluation of Medical Devices — Part 17: Toxicological Risk Assessment of Medical Device Constituents", "Toxicological risk assessment of device constituents."],
    ["IS/ISO 10993-18:2020", "Biological Evaluation of Medical Devices — Part 18: Chemical Characterization of Medical Device Materials within a Risk Management Process", "Chemical characterisation of device materials."],
    ["IS/ISO 10993-19:2020", "Biological Evaluation of Medical Devices — Part 19: Physico-Chemical, Morphological and Topographical Characterization of Materials", "Physico-chemical and morphological characterisation of materials."],
    ["IS/ISO 10993-23:2021", "Biological Evaluation of Medical Devices — Part 23: Tests for Irritation", "Irritation testing of medical devices."],
    ["IS/ISO 17665:2024", "Sterilization of Health Care Products — Moist Heat — Requirements for the Development, Validation and Routine Control of a Sterilization Process for Medical Devices", "Moist heat sterilisation process requirements."],
    ["IS/ISO 17664-1:2021", "Processing of Health Care Products — Information to Be Provided by the Medical Device Manufacturer for the Processing of Medical Devices — Part 1: Critical and Semi-Critical Medical Devices", "Reprocessing instructions for critical and semi-critical devices."],
    ["IS/ISO 17664-2:2021", "Processing of Health Care Products — Information to Be Provided by the Medical Device Manufacturer for the Processing of Medical Devices — Part 2: Non-Critical Medical Devices", "Reprocessing instructions for non-critical devices."],
    ["IS/ISO 7153-1:2016", "Surgical Instruments — Materials — Part 1: Metals", "Metals approved for surgical instrument manufacture."],
    ["IS/ISO 7864:2016", "Sterile Hypodermic Needles for Single Use — Requirements and Test Methods", "Sterile hypodermic needle dimensions and test methods."],
    ["IS/ISO 8537:2016", "Sterile Single-Use Syringes, with or without Needle, for Insulin", "Insulin syringe requirements and test methods."],
    ["IS/ISO 23908:2011", "Sharps Injury Protection — Requirements and Test Methods — Sharps Protection Features for Single-Use Hypodermic Needles, Introducers for Catheters and Needles Used for Blood Sampling", "Testing of sharps protection features."],
  ],
};

export const STD_WAVE17 = buildBlocks(
  QMS,
  ENVIRONMENT_AND_ENERGY,
  INFORMATION_AND_SERVICE,
  HEALTHCARE_AND_STERILIZATION,
);
