/* Extra catalogue wave 24 — closing wave: luminaires and lamp controlgear,
 * automatic electrical controls, explosive-atmosphere equipment, the remaining
 * governance/security management-system adoptions and hallmarking practice. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const LUMINAIRES: Block = {
  category: "electronics",
  rows: [
    ["IS/IEC 60598-1:2020", "Luminaires — Part 1: General Requirements and Tests", "General safety requirements for luminaires.", "C"],
    ["IS/IEC 60598-2-1:2019", "Luminaires — Part 2-1: Particular Requirements — Fixed General Purpose Luminaires", "Fixed general purpose luminaire requirements."],
    ["IS/IEC 60598-2-2:2011", "Luminaires — Part 2-2: Particular Requirements — Recessed Luminaires", "Recessed luminaire thermal and construction requirements."],
    ["IS/IEC 60598-2-3:2019", "Luminaires — Part 2-3: Particular Requirements — Luminaires for Road and Street Lighting", "Street and road lighting luminaire requirements."],
    ["IS/IEC 60598-2-4:2017", "Luminaires — Part 2-4: Particular Requirements — Portable General Purpose Luminaires", "Portable general purpose luminaires."],
    ["IS/IEC 60598-2-5:2015", "Luminaires — Part 2-5: Particular Requirements — Floodlights", "Floodlight construction, ingress protection and thermal tests."],
    ["IS/IEC 60598-2-6:1994", "Luminaires — Part 2-6: Particular Requirements — Luminaires with Built-In Transformers for Filament Lamps", "Luminaires with built-in filament lamp transformers."],
    ["IS/IEC 60598-2-7:1982", "Luminaires — Part 2-7: Particular Requirements — Portable Luminaires for Garden Use", "Portable garden luminaire requirements."],
    ["IS/IEC 60598-2-8:2013", "Luminaires — Part 2-8: Particular Requirements — Handlamps", "Handlamp mechanical and electrical requirements."],
    ["IS/IEC 60598-2-11:2013", "Luminaires — Part 2-11: Particular Requirements — Aquarium Luminaires", "Aquarium luminaire safety requirements."],
    ["IS/IEC 60598-2-12:2013", "Luminaires — Part 2-12: Particular Requirements — Mains Socket-Outlet Mounted Nightlights", "Nightlight requirements for socket-outlet mounting."],
    ["IS/IEC 60598-2-13:2006", "Luminaires — Part 2-13: Particular Requirements — Ground Recessed Luminaires", "Ground recessed luminaire ingress and impact requirements."],
    ["IS/IEC 60598-2-14:2009", "Luminaires — Part 2-14: Particular Requirements — Luminaires for Cold Cathode Tubular Discharge Lamps and Similar Equipment", "Cold cathode luminaire requirements."],
    ["IS/IEC 60598-2-17:2017", "Luminaires — Part 2-17: Particular Requirements — Luminaires for Stage Lighting, Television and Film Studios", "Studio and stage luminaire requirements."],
    ["IS/IEC 60598-2-18:1993", "Luminaires — Part 2-18: Particular Requirements — Luminaires for Swimming Pools and Similar Applications", "Swimming pool luminaire electrical safety."],
    ["IS/IEC 60598-2-19:1981", "Luminaires — Part 2-19: Particular Requirements — Air-Handling Luminaires", "Air-handling luminaire thermal and air-flow requirements."],
    ["IS/IEC 60598-2-20:2014", "Luminaires — Part 2-20: Particular Requirements — Lighting Chains", "Lighting chain and rope light requirements."],
    ["IS/IEC 60598-2-22:2021", "Luminaires — Part 2-22: Particular Requirements — Luminaires for Emergency Lighting", "Emergency luminaire requirements and testing."],
    ["IS/IEC 60598-2-23:2020", "Luminaires — Part 2-23: Particular Requirements — Extra-Low-Voltage Lighting Systems for Filament Lamps", "ELV lighting system requirements."],
    ["IS/IEC 60598-2-24:2013", "Luminaires — Part 2-24: Particular Requirements — Luminaires with Limited Surface Temperatures", "Luminaires with temperature-limited surfaces.", "C"],
    ["IS/IEC 60598-2-25:1994", "Luminaires — Part 2-25: Particular Requirements — Luminaires for Use in Clinical Areas of Hospitals and Health Care Buildings", "Clinical area luminaire requirements."],
    ["IS/IEC 61347-1:2015", "Lamp Controlgear — Part 1: General and Safety Requirements", "General and safety requirements for lamp controlgear."],
    ["IS/IEC 61347-2-1:2013", "Lamp Controlgear — Part 2-1: Particular Requirements for Starting Devices (Other than Glow Starters)", "Starting device requirements for discharge lamps."],
    ["IS/IEC 61347-2-2:2011", "Lamp Controlgear — Part 2-2: Particular Requirements for DC or AC Supplied Electronic Step-Down Converters for Filament Lamps", "Electronic step-down converters for filament lamps."],
    ["IS/IEC 61347-2-3:2011", "Lamp Controlgear — Part 2-3: Particular Requirements for AC and/or DC Supplied Electronic Controlgear for Fluorescent Lamps", "Electronic controlgear for fluorescent lamps."],
    ["IS/IEC 61347-2-7:2011", "Lamp Controlgear — Part 2-7: Particular Requirements for Battery Supplied Electronic Controlgear for Emergency Lighting", "Battery supplied emergency lighting controlgear."],
    ["IS/IEC 61347-2-8:2012", "Lamp Controlgear — Part 2-8: Particular Requirements for Ballasts for Fluorescent Lamps", "Electromagnetic ballast requirements for fluorescent lamps."],
    ["IS/IEC 61347-2-9:2012", "Lamp Controlgear — Part 2-9: Particular Requirements for Ballasts for Discharge Lamps (Excluding Fluorescent Lamps)", "Ballasts for HID discharge lamps."],
    ["IS/IEC 61347-2-10:2016", "Lamp Controlgear — Part 2-10: Particular Requirements for Electronic Inverters and Converters for High-Frequency Operation of Tubular Discharge Lamps", "High frequency inverter and converter requirements."],
    ["IS/IEC 61347-2-11:2014", "Lamp Controlgear — Part 2-11: Particular Requirements for Miscellaneous Electronic Circuits Used with Luminaires", "Miscellaneous electronic circuits used with luminaires."],
    ["IS/IEC 61347-2-12:2011", "Lamp Controlgear — Part 2-12: Particular Requirements for DC or AC Supplied Electronic Ballasts for Discharge Lamps (Excluding Fluorescent Lamps)", "Electronic ballasts for HID discharge lamps."],
    ["IS/IEC 61347-2-13:2016", "Lamp Controlgear — Part 2-13: Particular Requirements for DC or AC Supplied Electronic Controlgear for LED Modules", "Electronic LED driver requirements.", "C"],
    ["IS/IEC 60669-1:2018", "Switches for Household and Similar Fixed-Electrical Installations — Part 1: General Requirements", "General requirements for wall switches.", "M", { keywords: ["switch", "modular", "स्विच"] }],
    ["IS/IEC 60884-1:2006", "Plugs and Socket-Outlets for Household and Similar Purposes — Part 1: General Requirements", "Plugs and socket-outlet dimensions, safety and tests.", "M", { keywords: ["socket", "plug", "सॉकेट"] }],
    ["IS/IEC 60998-1:2003", "Connecting Devices for Low-Voltage Circuits for Household and Similar Purposes — Part 1: General Requirements", "General requirements for wire connecting devices."],
    ["IS/IEC 60998-2-1:2017", "Connecting Devices for Low-Voltage Circuits for Household and Similar Purposes — Part 2-1: Particular Requirements for Connecting Devices as Separate Entities with Screw-Type Clamping Units", "Screw-type clamping unit requirements."],
    ["IS/IEC 60998-2-2:2003", "Connecting Devices for Low-Voltage Circuits for Household and Similar Purposes — Part 2-2: Particular Requirements for Connecting Devices as Separate Entities with Screwless-Type Clamping Units", "Screwless clamping unit requirements."],
    ["IS/IEC 61558-1:2017", "Safety of Power Transformers, Power Supplies, Reactors and Similar Products — Part 1: General Requirements and Tests", "General safety requirements for small transformers and power supplies."],
    ["IS/IEC 61558-2-4:2009", "Safety of Transformers, Reactors, Power Supply Units and Similar Products — Part 2-4: Particular Requirements for Isolating Transformers and Safety Isolating Transformers", "Isolating and safety isolating transformer requirements."],
    ["IS/IEC 61558-2-6:2009", "Safety of Transformers, Reactors, Power Supply Units and Similar Products — Part 2-6: Particular Requirements for Safety Isolating Transformers for General Use", "General purpose safety isolating transformers."],
    ["IS/IEC 61558-2-16:2013", "Safety of Transformers, Reactors, Power Supply Units and Similar Products — Part 2-16: Particular Requirements for Switch Mode Power Supply Units and Transformers for Switch Mode Power Supply Units", "Switch mode power supply unit requirements.", "C"],
  ],
};

const AUTOMATIC_CONTROLS_AND_HAZARDOUS_AREA: Block = {
  category: "electrical",
  rows: [
    ["IS/IEC 60730-1:2015", "Automatic Electrical Controls — Part 1: General Requirements", "General requirements for automatic electrical controls."],
    ["IS/IEC 60730-2-2:2002", "Automatic Electrical Controls for Household and Similar Use — Part 2-2: Particular Requirements for Thermal Motor Protectors", "Thermal motor protector requirements."],
    ["IS/IEC 60730-2-3:2007", "Automatic Electrical Controls for Household and Similar Use — Part 2-3: Particular Requirements for Thermal Protectors for Ballasts for Tubular Fluorescent Lamps", "Thermal protectors for lamp ballasts."],
    ["IS/IEC 60730-2-4:2006", "Automatic Electrical Controls for Household and Similar Use — Part 2-4: Particular Requirements for Thermal Protectors for Motor-Compressors", "Thermal protectors for hermetically sealed motor-compressors."],
    ["IS/IEC 60730-2-5:2013", "Automatic Electrical Controls — Part 2-5: Particular Requirements for Automatic Electrical Burner Control Systems", "Automatic burner control system requirements."],
    ["IS/IEC 60730-2-6:2015", "Automatic Electrical Controls — Part 2-6: Particular Requirements for Automatic Electrical Pressure Sensing Controls", "Pressure sensing control requirements."],
    ["IS/IEC 60730-2-7:2008", "Automatic Electrical Controls for Household and Similar Use — Part 2-7: Particular Requirements for Timers and Time Switches", "Timer and time switch requirements."],
    ["IS/IEC 60730-2-8:2003", "Automatic Electrical Controls for Household and Similar Use — Part 2-8: Particular Requirements for Electrically Operated Water Valves", "Electrically operated water valve requirements."],
    ["IS/IEC 60730-2-9:2015", "Automatic Electrical Controls — Part 2-9: Particular Requirements for Temperature Sensing Controls", "Temperature sensing control requirements."],
    ["IS/IEC 60730-2-10:2007", "Automatic Electrical Controls for Household and Similar Use — Part 2-10: Particular Requirements for Motor Starting Relays", "Motor starting relay requirements."],
    ["IS/IEC 60730-2-11:2008", "Automatic Electrical Controls for Household and Similar Use — Part 2-11: Particular Requirements for Energy Regulators", "Energy regulator requirements."],
    ["IS/IEC 60730-2-12:2003", "Automatic Electrical Controls for Household and Similar Use — Part 2-12: Particular Requirements for Electrically Operated Door Locks", "Electrically operated door lock requirements."],
    ["IS/IEC 60730-2-13:2007", "Automatic Electrical Controls for Household and Similar Use — Part 2-13: Particular Requirements for Humidity Sensing Controls", "Humidity sensing control requirements."],
    ["IS/IEC 60730-2-15:2010", "Automatic Electrical Controls for Household and Similar Use — Part 2-15: Particular Requirements for Electrically Operated Air Valves", "Electrically operated air valve requirements."],
    ["IS/IEC 60730-2-17:2007", "Automatic Electrical Controls for Household and Similar Use — Part 2-17: Particular Requirements for Electrically Operated Gas Valves", "Electrically operated gas valve requirements."],
    ["IS/IEC 60079-6:2015", "Explosive Atmospheres — Part 6: Equipment Protection by Liquid Immersion 'o'", "Liquid immersion protection requirements for Ex equipment."],
    ["IS/IEC 60079-10-1:2015", "Explosive Atmospheres — Part 10-1: Classification of Areas — Explosive Gas Atmospheres", "Hazardous area classification for explosive gas atmospheres."],
    ["IS/IEC 60079-10-2:2015", "Explosive Atmospheres — Part 10-2: Classification of Areas — Explosive Dust Atmospheres", "Hazardous area classification for combustible dusts."],
    ["IS/IEC 60079-13:2017", "Explosive Atmospheres — Part 13: Equipment Protection by Pressurized Room 'p' and Artificially Ventilated Room 'v'", "Pressurized and ventilated room protection."],
    ["IS/IEC 60079-14:2014", "Explosive Atmospheres — Part 14: Electrical Installations Design, Selection and Erection", "Design, selection and erection of Ex installations."],
    ["IS/IEC 60079-17:2014", "Explosive Atmospheres — Part 17: Electrical Installations Inspection and Maintenance", "Inspection and maintenance of Ex installations."],
    ["IS/IEC 60079-25:2010", "Explosive Atmospheres — Part 25: Intrinsically Safe Electrical Systems", "Intrinsically safe system design requirements."],
    ["IS/IEC 60079-26:2014", "Explosive Atmospheres — Part 26: Equipment with Equipment Protection Level (EPL) Ga", "Equipment with the highest level of gas protection."],
    ["IS/IEC 60079-28:2015", "Explosive Atmospheres — Part 28: Protection of Equipment and Transmission Systems Using Optical Radiation", "Optical radiation protection in explosive atmospheres."],
    ["IS/IEC 60079-29-1:2016", "Explosive Atmospheres — Part 29-1: Gas Detectors — Performance Requirements of Detectors for Flammable Gases", "Performance requirements for flammable gas detectors."],
    ["IS/IEC 60079-30-1:2015", "Explosive Atmospheres — Part 30-1: Electrical Resistance Trace Heating — General and Testing Requirements", "Trace heating requirements for hazardous areas."],
    ["IS/IEC 60079-32-1:2017", "Explosive Atmospheres — Part 32-1: Electrostatic Hazards — Guidance", "Electrostatic hazard guidance for explosive atmospheres."],
    ["IS/IEC 60079-35-1:2011", "Explosive Atmospheres — Part 35-1: Caplights for Use in Mines Susceptible to Firedamp — General Requirements", "Caplight requirements for gassy mines."],
  ],
};

const SERVICES_CLOSING: Block = {
  category: "services",
  voluntaryScheme: "Management System Certification",
  rows: [
    ["IS/ISO/IEC 17024:2012", "Conformity Assessment — General Requirements for Bodies Operating Certification of Persons", "Competence and impartiality requirements for personnel certification bodies."],
    ["IS/ISO 28000:2022", "Security and Resilience — Security Management Systems — Requirements", "Security management system requirements for supply chains."],
    ["IS/ISO 28001:2007", "Security Management Systems for the Supply Chain — Best Practices for Implementing Supply Chain Security", "Best practice for implementing supply chain security."],
    ["IS/ISO 28002:2011", "Security Management Systems for the Supply Chain — Development of Resilience in the Supply Chain", "Developing supply chain resilience and recovery capability."],
    ["IS/ISO 18788:2015", "Management System for Private Security Operations — Requirements with Guidance for Use", "Management system requirements for private security operations."],
    ["IS/ISO 37002:2021", "Whistleblowing Management Systems — Guidelines", "Designing and operating a whistleblowing management system."],
    ["IS/ISO 29993:2017", "Learning Services outside Formal Education — Service Requirements", "Service requirements for non-formal learning providers."],
    ["IS/ISO 20387:2018", "Biotechnology — Biobanking — General Requirements for Biobanking", "General requirements for biobank quality and competence."],
    ["IS/ISO 22870:2016", "Point-of-Care Testing (POCT) — Requirements for Quality and Competence", "Quality and competence requirements for point-of-care testing."],
    ["IS/ISO 15190:2020", "Medical Laboratories — Requirements for Safety", "Biosafety requirements for medical laboratories."],
    ["IS/ISO 15197:2013", "In Vitro Diagnostic Test Systems — Requirements for Blood-Glucose Monitoring Systems for Self-Testing in Managing Diabetes Mellitus", "Blood glucose self-testing system performance requirements."],
    ["IS/ISO 14161:2009", "Sterilization of Health Care Products — Biological Indicators — Guidance for the Selection, Use and Interpretation of Results", "Selecting and interpreting biological indicator results."],
    ["IS/ISO 22317:2015", "Societal Security — Business Continuity Management Systems — Guidelines for Business Impact Analysis", "Conducting a business impact analysis."],
    ["IS/ISO 22320:2018", "Security and Resilience — Emergency Management — Guidelines for Incident Management", "Incident management guidance for emergency response."],
    ["IS/ISO 22324:2015", "Societal Security — Emergency Management — Guidelines for Colour-Coded Alerts", "Colour-coded alert design for public warnings."],
    ["IS/ISO 22325:2016", "Security and Resilience — Emergency Management — Guidelines for Capability Assessment for Emergency Management", "Assessing emergency management capability."],
    ["IS/ISO 14644-9:2022", "Cleanrooms and Associated Controlled Environments — Part 9: Assessment of Surface Cleanliness by Particle Concentration", "Surface cleanliness classification by particle concentration."],
    ["IS/ISO 14644-10:2022", "Cleanrooms and Associated Controlled Environments — Part 10: Assessment of Surface Cleanliness by Chemical Concentration", "Chemical surface cleanliness assessment for cleanrooms."],
    ["IS/ISO 14644-14:2016", "Cleanrooms and Associated Controlled Environments — Part 14: Assessment of Suitability for Use of Equipment by Airborne Particle Concentration", "Assessing equipment suitability for cleanroom use."],
    ["IS/ISO 14698-2:2003", "Cleanrooms and Associated Controlled Environments — Biocontamination Control — Part 2: Evaluation and Interpretation of Biocontamination Data", "Evaluating and interpreting biocontamination data."],
    ["IS/ISO 8601-1:2019", "Date and Time — Representations for Information Interchange — Part 1: Basic Rules", "Basic rules for date and time representation."],
    ["IS/ISO 8601-2:2019", "Date and Time — Representations for Information Interchange — Part 2: Extensions", "Extended date and time representations."],
    ["IS/ISO/IEC 15288:2015", "Systems and Software Engineering — System Life Cycle Processes", "System life-cycle processes for engineered systems."],
    ["IS/ISO/IEC 24748-1:2018", "Systems and Software Engineering — Life Cycle Management — Part 1: Guidelines for Life Cycle Management", "Life cycle management guidance."],
    ["IS/ISO/IEC 25012:2008", "Software Engineering — Software Product Quality Requirements and Evaluation (SQuaRE) — Data Quality Model", "Data quality model for software systems."],
    ["IS/ISO/IEC 25024:2015", "Systems and Software Engineering — Systems and Software Quality Requirements and Evaluation (SQuaRE) — Measurement of Data Quality", "Measuring data quality characteristics."],
    ["IS/ISO/IEC 29119-1:2021", "Software and Systems Engineering — Software Testing — Part 1: General Concepts", "General concepts for software testing."],
    ["IS/ISO/IEC 29119-2:2021", "Software and Systems Engineering — Software Testing — Part 2: Test Processes", "Test processes across the software life cycle."],
    ["IS/ISO/IEC 29119-3:2021", "Software and Systems Engineering — Software Testing — Part 3: Test Documentation", "Test documentation templates and content."],
    ["IS/ISO/IEC 19770-1:2017", "Information Technology — IT Asset Management — Part 1: IT Asset Management Systems — Requirements", "IT asset management system requirements."],
    ["IS/ISO/IEC 20000-3:2012", "Information Technology — Service Management — Part 3: Guidance on Scope Definition and Applicability of ISO/IEC 20000-1", "Scope definition and applicability guidance."],
    ["IS/ISO/IEC 27031:2011", "Information Technology — Security Techniques — Guidelines for Information and Communication Technology Readiness for Business Continuity", "ICT readiness for business continuity."],
    ["IS/ISO/IEC 27037:2012", "Information Technology — Security Techniques — Guidelines for Identification, Collection, Acquisition and Preservation of Digital Evidence", "Handling digital evidence for investigations."],
    ["IS/ISO/IEC 27799:2016", "Health Informatics — Information Security Management in Health Using ISO/IEC 27002", "Information security management for health information."],
    ["IS/ISO/IEC 29100:2011", "Information Technology — Security Techniques — Privacy Framework", "Privacy framework and safeguarding of personally identifiable information."],
    ["IS/ISO/IEC 29134:2017", "Information Technology — Security Techniques — Guidelines for Privacy Impact Assessment", "Conducting a privacy impact assessment."],
    ["IS/ISO/IEC 19941:2017", "Information Technology — Cloud Computing — Interoperability and Portability", "Cloud interoperability and portability requirements."],
    ["IS/ISO/IEC 38500:2015", "Information Technology — Governance of IT for the Organization", "Principles and model for governance of IT."],
    ["IS/ISO 50007:2017", "Energy Services — Guidelines for the Assessment and Improvement of the Energy Service to Users", "Assessing and improving energy services to users."],
  ],
};

const HALLMARKING_PRACTICE: Block = {
  category: "hallmark",
  rows: [
    ["IS 1417-1:2016", "Jewellery — Gold — Fineness and Marking — Part 1: Fineness Grades and Marking Requirements", "Permitted gold fineness grades and the marking symbols for each.", "V", { keywords: ["gold", "hallmark", "सोना", "हॉलमार्क"] }],
    ["IS 1417-2:2016", "Jewellery — Gold — Fineness and Marking — Part 2: Sampling of Gold Jewellery for Assay", "Sampling plans for assaying gold jewellery lots."],
    ["IS 1418-1:2022", "Methods of Test for Determination of Fineness of Gold — Part 1: Fire Assay (Cupellation) Method", "Reference fire assay method for gold fineness."],
    ["IS 1418-2:2022", "Methods of Test for Determination of Fineness of Gold — Part 2: X-Ray Fluorescence Spectrometry", "Non-destructive XRF determination of gold fineness."],
    ["IS 1418-3:2022", "Methods of Test for Determination of Fineness of Gold — Part 3: Touchstone Method", "Touchstone (touch needle) method for indicative fineness."],
    ["IS 2112-1:2014", "Jewellery — Silver — Fineness and Marking — Part 1: Fineness Grades and Marking", "Silver fineness grades and hallmarking requirements."],
    ["IS 2112-2:2014", "Jewellery — Silver — Fineness and Marking — Part 2: Assay Methods for Silver Jewellery", "Assay methods used for silver jewellery fineness."],
    ["IS 9529:2019", "Gold and Gold Alloy Solders for Jewellery — Specification", "Solder composition and fineness compatibility for gold jewellery."],
    ["IS 13782:2019", "Platinum Jewellery — Fineness and Marking — Specification", "Platinum fineness grades and marking requirements."],
    ["IS 14288:2019", "Gold Plated Jewellery — Specification", "Plating thickness, adhesion and marking for gold plated jewellery."],
    ["IS 2114:2019", "Hallmarking of Gold Jewellery — Code of Practice", "Hallmark components, licence references and counter-marking practice."],
    ["IS 16861:2018", "Jewellery — Determination of Nickel Release — Test Method", "Nickel release testing for jewellery in prolonged skin contact."],
    ["IS 17036:2018", "Gemstones and Jewellery — Terminology", "Standard terminology used for gemstones and jewellery trade."],
  ],
};

export const STD_WAVE24 = buildBlocks(
  LUMINAIRES,
  AUTOMATIC_CONTROLS_AND_HAZARDOUS_AREA,
  SERVICES_CLOSING,
  HALLMARKING_PRACTICE,
);
