/* Extra catalogue wave 19 — medical electrical equipment (IS/IEC 60601 series)
 * and the household-appliance safety parts of the IS 302-2 series that Indian
 * consumer-product questions keep running into. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const MEDICAL_ELECTRICAL: Block = {
  category: "electronics",
  rows: [
    ["IS/IEC 60601-1-3:2014", "Medical Electrical Equipment — Part 1-3: General Requirements for Basic Safety and Essential Performance — Collateral Standard: Radiation Protection in Diagnostic X-Ray Equipment", "Radiation protection for diagnostic X-ray equipment."],
    ["IS/IEC 60601-1-8:2013", "Medical Electrical Equipment — Part 1-8: General Requirements for Basic Safety and Essential Performance — Collateral Standard: General Requirements, Tests and Guidance for Alarm Systems in Medical Electrical Equipment and Medical Electrical Systems", "Alarm system requirements for medical electrical equipment."],
    ["IS/IEC 60601-1-9:2013", "Medical Electrical Equipment — Part 1-9: General Requirements for Basic Safety and Essential Performance — Collateral Standard: Requirements for Environmentally Conscious Design", "Environmentally conscious design of medical electrical equipment."],
    ["IS/IEC 60601-1-10:2014", "Medical Electrical Equipment — Part 1-10: General Requirements for Basic Safety and Essential Performance — Collateral Standard: Requirements for the Development of Physiologic Closed-Loop Controllers", "Development of physiological closed-loop controllers."],
    ["IS/IEC 60601-1-12:2014", "Medical Electrical Equipment — Part 1-12: General Requirements for Basic Safety and Essential Performance — Collateral Standard: Requirements for Medical Electrical Equipment and Medical Electrical Systems Intended for Use in the Emergency Medical Services Environment", "Equipment intended for the emergency medical services environment."],
    ["IS/IEC 60601-2-3:2015", "Medical Electrical Equipment — Part 2-3: Particular Requirements for the Basic Safety and Essential Performance of Short-Wave Therapy Equipment", "Short-wave therapy equipment safety and performance."],
    ["IS/IEC 60601-2-6:2016", "Medical Electrical Equipment — Part 2-6: Particular Requirements for the Basic Safety and Essential Performance of Microwave Therapy Equipment", "Microwave therapy equipment requirements."],
    ["IS/IEC 60601-2-7:2015", "Medical Electrical Equipment — Part 2-7: Particular Requirements for the Basic Safety and Essential Performance of High-Voltage Generators of Diagnostic X-Ray Generators", "High-voltage generators of diagnostic X-ray equipment."],
    ["IS/IEC 60601-2-9:2016", "Medical Electrical Equipment — Part 2-9: Particular Requirements for the Basic Safety and Essential Performance of Equipment for Dosimetric Instruments Used in Radiotherapy", "Dosimetric instruments used with patient contact in radiotherapy."],
    ["IS/IEC 60601-2-10:2014", "Medical Electrical Equipment — Part 2-10: Particular Requirements for the Basic Safety and Essential Performance of Nerve and Muscle Stimulators", "Nerve and muscle stimulator requirements."],
    ["IS/IEC 60601-2-11:2015", "Medical Electrical Equipment — Part 2-11: Particular Requirements for the Basic Safety and Essential Performance of Gamma Beam Therapy Equipment", "Gamma beam therapy equipment requirements."],
    ["IS/IEC 60601-2-13:2014", "Medical Electrical Equipment — Part 2-13: Particular Requirements for the Basic Safety and Essential Performance of Anaesthetic Systems", "Anaesthetic system safety and performance."],
    ["IS/IEC 60601-2-14:2015", "Medical Electrical Equipment — Part 2-14: Particular Requirements for the Basic Safety and Essential Performance of Electroconvulsive Therapy Equipment", "Electroconvulsive therapy equipment requirements."],
    ["IS/IEC 60601-2-17:2014", "Medical Electrical Equipment — Part 2-17: Particular Requirements for the Basic Safety and Essential Performance of Automatically-Controlled Brachytherapy Afterloading Equipment", "Automatically controlled brachytherapy afterloading equipment."],
    ["IS/IEC 60601-2-21:2016", "Medical Electrical Equipment — Part 2-21: Particular Requirements for the Basic Safety and Essential Performance of Infant Radiant Warmers", "Infant radiant warmer requirements."],
    ["IS/IEC 60601-2-23:2015", "Medical Electrical Equipment — Part 2-23: Particular Requirements for the Basic Safety and Essential Performance of Transcutaneous Partial Pressure Monitoring Equipment", "Transcutaneous partial pressure monitoring equipment."],
    ["IS/IEC 60601-2-26:2015", "Medical Electrical Equipment — Part 2-26: Particular Requirements for the Basic Safety and Essential Performance of Electroencephalographs", "Electroencephalograph requirements and performance tests."],
    ["IS/IEC 60601-2-28:2014", "Medical Electrical Equipment — Part 2-28: Particular Requirements for the Basic Safety and Essential Performance of X-Ray Tube Assemblies and X-Ray Source Assemblies for Medical Diagnosis", "X-ray tube and source assembly requirements."],
    ["IS/IEC 60601-2-29:2014", "Medical Electrical Equipment — Part 2-29: Particular Requirements for the Basic Safety and Essential Performance of Radiotherapy Simulators", "Radiotherapy simulator requirements."],
    ["IS/IEC 60601-2-31:2014", "Medical Electrical Equipment — Part 2-31: Particular Requirements for the Basic Safety and Essential Performance of External Cardiac Pacemakers with Internal Power Source", "External cardiac pacemakers with internal power source."],
    ["IS/IEC 60601-2-32:2014", "Medical Electrical Equipment — Part 2-32: Particular Requirements for the Basic Safety and Essential Performance of Associated Equipment of X-Ray Equipment", "Associated equipment of X-ray equipment."],
    ["IS/IEC 60601-2-33:2015", "Medical Electrical Equipment — Part 2-33: Particular Requirements for the Basic Safety and Essential Performance of Magnetic Resonance Equipment for Medical Diagnosis", "Magnetic resonance equipment for medical diagnosis."],
    ["IS/IEC 60601-2-35:2015", "Medical Electrical Equipment — Part 2-35: Particular Requirements for the Basic Safety and Essential Performance of Heating Devices Using Blankets, Pads, Clothing and Mattresses", "Blanket, pad and mattress heating devices."],
    ["IS/IEC 60601-2-43:2014", "Medical Electrical Equipment — Part 2-43: Particular Requirements for the Basic Safety and Essential Performance of X-Ray Equipment for Interventional Procedures", "X-ray equipment used for interventional procedures."],
    ["IS/IEC 60601-2-46:2016", "Medical Electrical Equipment — Part 2-46: Particular Requirements for the Basic Safety and Essential Performance of Operating Tables", "Operating table requirements."],
    ["IS/IEC 60601-2-52:2015", "Medical Electrical Equipment — Part 2-52: Particular Requirements for the Basic Safety and Essential Performance of Medical Beds", "Medical bed safety and performance requirements."],
    ["IS/IEC 60601-2-54:2015", "Medical Electrical Equipment — Part 2-54: Particular Requirements for the Basic Safety and Essential Performance of X-Ray Equipment for Radiography and Radioscopy", "X-ray equipment for radiography and radioscopy."],
    ["IS/IEC 60601-2-55:2015", "Medical Electrical Equipment — Part 2-55: Particular Requirements for the Basic Safety and Essential Performance of Respiratory Gas Monitors", "Respiratory gas monitor requirements."],
    ["IS/IEC 60601-2-56:2016", "Medical Electrical Equipment — Part 2-56: Particular Requirements for the Basic Safety and Essential Performance of Clinical Thermometers for Body Temperature Measurement", "Clinical thermometer requirements."],
    ["IS/IEC 60601-2-57:2014", "Medical Electrical Equipment — Part 2-57: Particular Requirements for the Basic Safety and Essential Performance of Non-Laser Light Source Equipment Intended for Therapeutic, Diagnostic, Monitoring and Cosmetic/Aesthetic Use", "Non-laser light source equipment for clinical and aesthetic use."],
    ["IS/IEC 60601-2-59:2014", "Medical Electrical Equipment — Part 2-59: Particular Requirements for the Basic Safety and Essential Performance of Screening Thermographs for Human Febrile Temperature Screening", "Screening thermographs used for febrile temperature screening."],
    ["IS/IEC 60601-2-60:2015", "Medical Electrical Equipment — Part 2-60: Particular Requirements for the Basic Safety and Essential Performance of Dental Equipment", "Dental equipment safety and performance."],
    ["IS/IEC 60601-2-62:2015", "Medical Electrical Equipment — Part 2-62: Particular Requirements for the Basic Safety and Essential Performance of High Intensity Therapeutic Ultrasound (HITU) Equipment", "High intensity therapeutic ultrasound equipment."],
    ["IS/IEC 60601-2-63:2015", "Medical Electrical Equipment — Part 2-63: Particular Requirements for the Basic Safety and Essential Performance of Dental Extra-Oral X-Ray Equipment", "Dental extra-oral X-ray equipment."],
    ["IS/IEC 60601-2-64:2015", "Medical Electrical Equipment — Part 2-64: Particular Requirements for the Basic Safety and Essential Performance of Light Ion Beam Medical Electrical Equipment", "Light ion beam therapy equipment."],
    ["IS/IEC 60601-2-65:2015", "Medical Electrical Equipment — Part 2-65: Particular Requirements for the Basic Safety and Essential Performance of Dental Intra-Oral X-Ray Equipment", "Dental intra-oral X-ray equipment."],
    ["IS/IEC 60601-2-66:2015", "Medical Electrical Equipment — Part 2-66: Particular Requirements for the Basic Safety and Essential Performance of Hearing Instruments and Hearing Instrument Systems", "Hearing instrument safety and performance."],
    ["IS/IEC 60601-2-70:2015", "Medical Electrical Equipment — Part 2-70: Particular Requirements for the Basic Safety and Essential Performance of Sleep Apnoea Breathing Therapy Equipment", "Sleep apnoea breathing therapy equipment."],
    ["IS/ISO 80601-2-12:2020", "Medical Electrical Equipment — Part 2-12: Particular Requirements for Basic Safety and Essential Performance of Critical Care Ventilators", "Critical care ventilator safety and performance.", "C"],
    ["IS/ISO 80601-2-69:2014", "Medical Electrical Equipment — Part 2-69: Particular Requirements for Basic Safety and Essential Performance of Oxygen Concentrator Equipment", "Oxygen concentrator safety and performance."],
    ["IS/ISO 80601-2-80:2018", "Medical Electrical Equipment — Part 2-80: Particular Requirements for Basic Safety and Essential Performance of Ventilatory Support Equipment for Ventilatory Impairment", "Ventilatory support equipment for ventilatory impairment."],
    ["IS/ISO 80601-2-84:2020", "Medical Electrical Equipment — Part 2-84: Particular Requirements for the Basic Safety and Essential Performance of Ventilators for Emergency Medical Services Environment", "Ventilators for the emergency medical services environment."],
  ],
};

const APPLIANCE_SAFETY: Block = {
  category: "consumer",
  rows: [
    ["IS 302-2-5:2009", "Safety of Household and Similar Electrical Appliances — Part 2-5: Particular Requirements for Dishwashers", "Dishwasher electrical safety requirements."],
    ["IS 302-2-10:2009", "Safety of Household and Similar Electrical Appliances — Part 2-10: Particular Requirements for Floor Treatment Machines and Wet Scrubbing Machines", "Floor treatment and wet scrubbing machine safety."],
    ["IS 302-2-16:2009", "Safety of Household and Similar Electrical Appliances — Part 2-16: Particular Requirements for Food Waste Disposers", "Food waste disposer safety requirements."],
    ["IS 302-2-17:2009", "Safety of Household and Similar Electrical Appliances — Part 2-17: Particular Requirements for Blankets, Pads, Clothing and Similar Flexible Heating Appliances", "Flexible heating appliance safety."],
    ["IS 302-2-21:2009", "Safety of Household and Similar Electrical Appliances — Part 2-21: Particular Requirements for Storage Water Heaters", "Storage water heater safety requirements.", "V", { keywords: ["geyser", "water heater", "गीज़र"] }],
    ["IS 302-2-26:2009", "Safety of Household and Similar Electrical Appliances — Part 2-26: Particular Requirements for Clocks", "Mains-operated clock safety requirements."],
    ["IS 302-2-27:2009", "Safety of Household and Similar Electrical Appliances — Part 2-27: Particular Requirements for Appliances for Skin Exposure to Ultraviolet and Infrared Radiation", "Skin exposure appliances using UV and IR radiation."],
    ["IS 302-2-28:2009", "Safety of Household and Similar Electrical Appliances — Part 2-28: Particular Requirements for Sewing Machines", "Sewing machine electrical safety."],
    ["IS 302-2-29:2014", "Safety of Household and Similar Electrical Appliances — Part 2-29: Particular Requirements for Battery Chargers", "Battery charger safety requirements.", "C", { keywords: ["charger", "battery", "चार्जर"] }],
    ["IS 302-2-31:2014", "Safety of Household and Similar Electrical Appliances — Part 2-31: Particular Requirements for Range Hoods and Other Cooking Fume Extractors", "Kitchen chimney and fume extractor safety."],
    ["IS 302-2-33:2009", "Safety of Household and Similar Electrical Appliances — Part 2-33: Particular Requirements for Coffee Mills and Coffee Grinders", "Coffee mill and grinder safety requirements."],
    ["IS 302-2-35:2009", "Safety of Household and Similar Electrical Appliances — Part 2-35: Particular Requirements for Instantaneous Water Heaters", "Instantaneous water heater safety requirements."],
    ["IS 302-2-36:2009", "Safety of Household and Similar Electrical Appliances — Part 2-36: Particular Requirements for Commercial Electric Cooking Ranges, Ovens, Hobs and Hob Elements", "Commercial cooking range safety."],
    ["IS 302-2-37:2009", "Safety of Household and Similar Electrical Appliances — Part 2-37: Particular Requirements for Commercial Electric Deep Fat Fryers", "Commercial deep fat fryer safety."],
    ["IS 302-2-38:2009", "Safety of Household and Similar Electrical Appliances — Part 2-38: Particular Requirements for Commercial Electric Griddles and Griddle Grills", "Commercial griddle safety requirements."],
    ["IS 302-2-41:2009", "Safety of Household and Similar Electrical Appliances — Part 2-41: Particular Requirements for Pumps for Liquids Having a Temperature Not Exceeding 35 °C", "Liquid pump safety for domestic and similar use."],
    ["IS 302-2-42:2009", "Safety of Household and Similar Electrical Appliances — Part 2-42: Particular Requirements for Commercial Electric Forced Convection Ovens, Steam Cookers and Steam-Convection Ovens", "Commercial oven and steamer safety."],
    ["IS 302-2-43:2009", "Safety of Household and Similar Electrical Appliances — Part 2-43: Particular Requirements for Clothes Dryers and Towel Rails", "Clothes dryer and towel rail safety."],
    ["IS 302-2-44:2009", "Safety of Household and Similar Electrical Appliances — Part 2-44: Particular Requirements for Ironers", "Ironer safety requirements."],
    ["IS 302-2-47:2009", "Safety of Household and Similar Electrical Appliances — Part 2-47: Particular Requirements for Commercial Electric Cooking Appliances Immersed in Oil", "Commercial oil-immersed cooking appliance safety."],
    ["IS 302-2-48:2009", "Safety of Household and Similar Electrical Appliances — Part 2-48: Particular Requirements for Commercial Electric Grillers and Toasters", "Commercial grill and toaster safety."],
    ["IS 302-2-49:2009", "Safety of Household and Similar Electrical Appliances — Part 2-49: Particular Requirements for Commercial Electric Appliances for Keeping Food and Crockery Warm", "Commercial hot-holding appliance safety."],
    ["IS 302-2-50:2009", "Safety of Household and Similar Electrical Appliances — Part 2-50: Particular Requirements for Commercial Electric Bains-Marie", "Commercial bain-marie safety requirements."],
    ["IS 302-2-52:2009", "Safety of Household and Similar Electrical Appliances — Part 2-52: Particular Requirements for Oral Hygiene Appliances", "Oral hygiene appliance safety."],
    ["IS 302-2-53:2009", "Safety of Household and Similar Electrical Appliances — Part 2-53: Particular Requirements for Sauna Heating Appliances", "Sauna heater safety requirements."],
    ["IS 302-2-54:2014", "Safety of Household and Similar Electrical Appliances — Part 2-54: Particular Requirements for Surface-Cleaning Appliances Employing Liquids", "Surface-cleaning appliances using liquids."],
    ["IS 302-2-55:2009", "Safety of Household and Similar Electrical Appliances — Part 2-55: Particular Requirements for Electrical Appliances for Use with Aquariums and Garden Ponds", "Aquarium and garden pond appliance safety."],
    ["IS 302-2-56:2009", "Safety of Household and Similar Electrical Appliances — Part 2-56: Particular Requirements for Projectors and Similar Appliances", "Projector safety requirements."],
    ["IS 302-2-59:2009", "Safety of Household and Similar Electrical Appliances — Part 2-59: Particular Requirements for Insect Killers", "Insect killer safety requirements."],
    ["IS 302-2-60:2009", "Safety of Household and Similar Electrical Appliances — Part 2-60: Particular Requirements for Whirlpool Baths and Whirlpool Spas", "Whirlpool bath and spa safety."],
    ["IS 302-2-61:2009", "Safety of Household and Similar Electrical Appliances — Part 2-61: Particular Requirements for Thermal-Storage Room Heaters", "Thermal storage room heater safety."],
    ["IS 302-2-65:2009", "Safety of Household and Similar Electrical Appliances — Part 2-65: Particular Requirements for Air-Cleaning Appliances", "Air purifier and air cleaner safety."],
    ["IS 302-2-66:2009", "Safety of Household and Similar Electrical Appliances — Part 2-66: Particular Requirements for Water-Bed Heating Appliances", "Water-bed heating appliance safety."],
    ["IS 302-2-67:2009", "Safety of Household and Similar Electrical Appliances — Part 2-67: Particular Requirements for Floor Treatment Machines for Commercial Use", "Commercial floor treatment machine safety."],
    ["IS 302-2-70:2009", "Safety of Household and Similar Electrical Appliances — Part 2-70: Particular Requirements for Milking Machines", "Milking machine safety requirements."],
    ["IS 302-2-71:2009", "Safety of Household and Similar Electrical Appliances — Part 2-71: Particular Requirements for Electrical Heating Appliances for Breeding and Rearing Animals", "Animal breeding and rearing heater safety."],
    ["IS 302-2-73:2009", "Safety of Household and Similar Electrical Appliances — Part 2-73: Particular Requirements for Fixed Immersion Heaters", "Fixed immersion heater safety."],
    ["IS 302-2-74:2009", "Safety of Household and Similar Electrical Appliances — Part 2-74: Particular Requirements for Portable Immersion Heaters", "Portable immersion heater safety requirements."],
    ["IS 302-2-75:2009", "Safety of Household and Similar Electrical Appliances — Part 2-75: Particular Requirements for Commercial Dispensing Appliances and Vending Machines", "Vending machine and dispensing appliance safety."],
    ["IS 302-2-76:2009", "Safety of Household and Similar Electrical Appliances — Part 2-76: Particular Requirements for Electric Fence Energizers", "Electric fence energizer safety."],
    ["IS 302-2-77:2009", "Safety of Household and Similar Electrical Appliances — Part 2-77: Particular Requirements for Pedestrian Controlled Mains-Operated Lawnmowers", "Pedestrian controlled lawnmower safety."],
    ["IS 302-2-78:2009", "Safety of Household and Similar Electrical Appliances — Part 2-78: Particular Requirements for Outdoor Barbecues", "Outdoor barbecue appliance safety."],
    ["IS 302-2-79:2014", "Safety of Household and Similar Electrical Appliances — Part 2-79: Particular Requirements for High Pressure Cleaners and Steam Cleaners", "High pressure cleaner safety.", "V", { keywords: ["pressure washer", "cleaner"] }],
    ["IS 302-2-81:2009", "Safety of Household and Similar Electrical Appliances — Part 2-81: Particular Requirements for Foot Warmers and Heating Mats", "Foot warmer and heating mat safety."],
    ["IS 302-2-82:2009", "Safety of Household and Similar Electrical Appliances — Part 2-82: Particular Requirements for Amusement Machines and Personal Service Machines", "Amusement and service machine safety."],
    ["IS 302-2-83:2009", "Safety of Household and Similar Electrical Appliances — Part 2-83: Particular Requirements for Heated Gullies", "Heated gully safety requirements."],
    ["IS 302-2-84:2009", "Safety of Household and Similar Electrical Appliances — Part 2-84: Particular Requirements for Toilet Appliances", "Toilet appliance safety, including bidet seats."],
    ["IS 302-2-85:2009", "Safety of Household and Similar Electrical Appliances — Part 2-85: Particular Requirements for Fabric Steamers", "Fabric steamer and garment steamer safety."],
    ["IS 302-2-88:2009", "Safety of Household and Similar Electrical Appliances — Part 2-88: Particular Requirements for Humidifiers for Heating, Ventilation or Air-Conditioning Systems", "Humidifier safety for HVAC systems."],
    ["IS 302-2-90:2009", "Safety of Household and Similar Electrical Appliances — Part 2-90: Particular Requirements for Commercial Microwave Ovens", "Commercial microwave oven safety."],
    ["IS 302-2-91:2009", "Safety of Household and Similar Electrical Appliances — Part 2-91: Particular Requirements for Walk-Behind and Hand-Held Lawn Scarifiers and Lawn Edge Trimmers", "Scarifier and edge trimmer safety."],
    ["IS 302-2-94:2009", "Safety of Household and Similar Electrical Appliances — Part 2-94: Particular Requirements for Scissors Type Grass Shears", "Scissors type grass shear safety."],
    ["IS 302-2-95:2009", "Safety of Household and Similar Electrical Appliances — Part 2-95: Particular Requirements for Drives for Vertically Moving Garage Doors for Residential Use", "Garage door drive safety."],
    ["IS 302-2-96:2009", "Safety of Household and Similar Electrical Appliances — Part 2-96: Particular Requirements for Flexible Sheet Heating Elements for Room Heating", "Flexible sheet heating element safety."],
    ["IS 302-2-97:2009", "Safety of Household and Similar Electrical Appliances — Part 2-97: Particular Requirements for Drives for Rolling Shutters, Awnings, Blinds and Similar Equipment", "Rolling shutter and blind drive safety."],
    ["IS 302-2-98:2009", "Safety of Household and Similar Electrical Appliances — Part 2-98: Particular Requirements for Humidifiers", "Domestic humidifier safety requirements."],
    ["IS 302-2-102:2009", "Safety of Household and Similar Electrical Appliances — Part 2-102: Particular Requirements for Gas, Oil and Solid-Fuel Burning Appliances Having Electrical Connections", "Electrical safety of gas, oil and solid-fuel appliances."],
    ["IS 302-2-103:2009", "Safety of Household and Similar Electrical Appliances — Part 2-103: Particular Requirements for Drives for Gates, Doors and Barriers", "Gate, door and barrier drive safety."],
    ["IS 302-2-104:2009", "Safety of Household and Similar Electrical Appliances — Part 2-104: Particular Requirements for Appliances to Recover and/or Recycle Refrigerant from Air-Conditioning and Refrigeration Equipment", "Refrigerant recovery and recycling appliance safety."],
    ["IS 302-2-105:2009", "Safety of Household and Similar Electrical Appliances — Part 2-105: Particular Requirements for Multifunction Shower Cabins", "Multifunction shower cabin safety."],
    ["IS 302-2-108:2009", "Safety of Household and Similar Electrical Appliances — Part 2-108: Particular Requirements for Electrolysers", "Electrolyser appliance safety requirements."],
    ["IS 302-2-109:2009", "Safety of Household and Similar Electrical Appliances — Part 2-109: Particular Requirements for UV Radiation Water Treatment Appliances", "UV water treatment appliance safety."],
    ["IS 302-2-110:2014", "Safety of Household and Similar Electrical Appliances — Part 2-110: Particular Requirements for Commercial Microwave Appliances with Convection Heating", "Commercial convection microwave appliance safety."],
  ],
};

export const STD_WAVE19 = buildBlocks(MEDICAL_ELECTRICAL, APPLIANCE_SAFETY);
