/* Extra catalogue wave 18 — IEC-adopted electrical and electronic equipment
 * standards: power and instrument transformers, LV assemblies, switchgear,
 * fuses, protection devices, rotating machines, cable test methods, solar and
 * EV charging equipment, plus electronics safety, environmental testing and
 * medical electrical equipment parts. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const CABLE_QCO = "Electrical Wires, Cables, Appliances and Protection Devices (Quality Control) Order";

const TRANSFORMERS_AND_SWITCHGEAR: Block = {
  category: "electrical",
  rows: [
    ["IS/IEC 60076-1:2011", "Power Transformers — Part 1: General", "General requirements, ratings and service conditions for power transformers."],
    ["IS/IEC 60076-2:2011", "Power Transformers — Part 2: Temperature Rise for Liquid-Immersed Transformers", "Limits of temperature rise determined by test and calculation."],
    ["IS/IEC 60076-3:2013", "Power Transformers — Part 3: Insulation Levels, Dielectric Tests and External Clearances in Air", "Insulation levels and dielectric test requirements."],
    ["IS/IEC 60076-4:2002", "Power Transformers — Part 4: Guide to the Lightning Impulse and Switching Impulse Testing", "Impulse test circuits and waveform evaluation."],
    ["IS/IEC 60076-5:2006", "Power Transformers — Part 5: Ability to Withstand Short Circuit", "Short-circuit withstand capability and demonstrated test evidence."],
    ["IS/IEC 60076-6:2007", "Power Transformers — Part 6: Reactors", "Requirements for shunt and series reactors."],
    ["IS/IEC 60076-7:2018", "Power Transformers — Part 7: Loading Guide for Mineral-Oil-Immersed Power Transformers", "Thermal model and loading limits for oil-immersed units."],
    ["IS/IEC 60076-10:2016", "Power Transformers — Part 10: Determination of Sound Levels", "Sound power and pressure level determination for transformers."],
    ["IS/IEC 60076-11:2018", "Power Transformers — Part 11: Dry-Type Transformers", "Requirements for dry-type power transformers including climactic classes."],
    ["IS/IEC 60076-12:2008", "Power Transformers — Part 12: Loading Guide for Dry-Type Power Transformers", "Loading guidance for dry-type transformers."],
    ["IS/IEC 60076-13:2006", "Power Transformers — Part 13: Self-Protected Liquid-Filled Transformers", "Self-protection requirements for liquid-filled distribution units."],
    ["IS/IEC 60076-14:2013", "Power Transformers — Part 14: Liquid-Immersed Power Transformers Using High-Temperature Insulation Materials", "Design and test requirements for high-temperature insulation systems."],
    ["IS/IEC 60076-16:2011", "Power Transformers — Part 16: Transformers for Wind Turbine Applications", "Special requirements for wind turbine transformers."],
    ["IS/IEC 61439-1:2020", "Low-Voltage Switchgear and Controlgear Assemblies — Part 1: General Rules", "General rules for design verification and routine verification of assemblies."],
    ["IS/IEC 61439-2:2020", "Low-Voltage Switchgear and Controlgear Assemblies — Part 2: Power Switchgear and Controlgear Assemblies", "Requirements for power switchgear and controlgear assemblies."],
    ["IS/IEC 61439-3:2012", "Low-Voltage Switchgear and Controlgear Assemblies — Part 3: Distribution Boards Intended to Be Operated by Ordinary Persons", "Distribution boards accessible to ordinary persons."],
    ["IS/IEC 61439-4:2012", "Low-Voltage Switchgear and Controlgear Assemblies — Part 4: Particular Requirements for Assemblies for Construction Sites", "Site distribution assemblies for construction and demolition work."],
    ["IS/IEC 61439-5:2014", "Low-Voltage Switchgear and Controlgear Assemblies — Part 5: Assemblies for Power Distribution in Public Networks", "Cable distribution cabinets and public network assemblies."],
    ["IS/IEC 61439-6:2012", "Low-Voltage Switchgear and Controlgear Assemblies — Part 6: Busbar Trunking Systems", "Busbar trunking system verification and ratings."],
    ["IS/IEC 60947-5-2:2013", "Low-Voltage Switchgear and Controlgear — Part 5-2: Control Circuit Devices and Switching Elements — Proximity Switches", "Proximity switch requirements and test methods."],
    ["IS/IEC 60947-5-3:2013", "Low-Voltage Switchgear and Controlgear — Part 5-3: Control Circuit Devices and Switching Elements — Requirements for Proximity Devices with Defined Behaviour under Fault Conditions", "Proximity devices with defined fault behaviour for safety applications."],
    ["IS/IEC 60947-5-4:2002", "Low-Voltage Switchgear and Controlgear — Part 5-4: Control Circuit Devices and Switching Elements — Method of Assessing the Performance of Low-Energy Contacts", "Low-energy contact performance assessment."],
    ["IS/IEC 60947-5-5:2016", "Low-Voltage Switchgear and Controlgear — Part 5-5: Control Circuit Devices and Switching Elements — Electrical Emergency Stop Device with Mechanical Latching Function", "Emergency stop devices with mechanical latching."],
    ["IS/IEC 60947-5-7:2013", "Low-Voltage Switchgear and Controlgear — Part 5-7: Control Circuit Devices and Switching Elements — Requirements for Proximity Devices with Analogue Output", "Proximity devices with analogue output signals."],
    ["IS/IEC 60947-5-8:2006", "Low-Voltage Switchgear and Controlgear — Part 5-8: Control Circuit Devices and Switching Elements — Three-Position Enabling Switches", "Three-position enabling switches for machinery control."],
    ["IS/IEC 60947-6-1:2013", "Low-Voltage Switchgear and Controlgear — Part 6-1: Multiple Function Equipment — Transfer Switching Equipment", "Automatic and manual transfer switching equipment."],
    ["IS/IEC 60947-6-2:2007", "Low-Voltage Switchgear and Controlgear — Part 6-2: Multiple Function Equipment — Control and Protective Switching Devices", "Control and protective switching devices (CPS) requirements."],
    ["IS/IEC 60947-7-1:2019", "Low-Voltage Switchgear and Controlgear — Part 7-1: Ancillary Equipment — Terminal Blocks for Copper Conductors", "Terminal block requirements for copper conductors."],
    ["IS/IEC 60947-7-2:2013", "Low-Voltage Switchgear and Controlgear — Part 7-2: Ancillary Equipment — Protective Conductor Terminal Blocks for Copper Conductors", "Protective conductor terminal block requirements."],
    ["IS/IEC 60947-7-3:2012", "Low-Voltage Switchgear and Controlgear — Part 7-3: Ancillary Equipment — Safety Requirements for Fuse Terminal Blocks", "Fuse terminal block safety requirements."],
    ["IS/IEC 60947-8:2011", "Low-Voltage Switchgear and Controlgear — Part 8: Control Units for Built-In Thermal Protection for Rotating Electrical Machines", "Thermal protection control units for rotating machines."],
    ["IS/IEC 60269-1:2014", "Low-Voltage Fuses — Part 1: General Requirements", "General requirements for LV fuse systems."],
    ["IS/IEC 60269-2:2016", "Low-Voltage Fuses — Part 2: Supplementary Requirements for Fuses for Use by Authorized Persons", "Fuses for use by authorized persons (industrial fuses)."],
    ["IS/IEC 60269-3:2018", "Low-Voltage Fuses — Part 3: Supplementary Requirements for Fuses for Use by Unskilled Persons", "Household and similar fuse requirements."],
    ["IS/IEC 60269-4:2018", "Low-Voltage Fuses — Part 4: Supplementary Requirements for Fuse-Links for the Protection of Semiconductor Devices", "Semiconductor protection fuse-links."],
    ["IS/IEC 60269-6:2010", "Low-Voltage Fuses — Part 6: Supplementary Requirements for Fuse-Links for the Protection of Solar Photovoltaic Energy Systems", "PV array and string protection fuse-links."],
    ["IS/IEC 61008-1:2016", "Residual Current Operated Circuit-Breakers without Integral Overcurrent Protection for Household and Similar Uses (RCCBs) — Part 1: General Rules", "RCCB general requirements and test sequences."],
    ["IS/IEC 61008-2-1:2016", "Residual Current Operated Circuit-Breakers without Integral Overcurrent Protection (RCCBs) — Part 2-1: Applicability of the General Rules to RCCBs Functionally Independent of Line Voltage", "RCCBs functionally independent of line voltage."],
    ["IS/IEC 61009-1:2016", "Residual Current Operated Circuit-Breakers with Integral Overcurrent Protection for Household and Similar Uses (RCBOs) — Part 1: General Rules", "RCBO requirements covering residual and overcurrent protection."],
    ["IS/IEC 61009-2-1:2016", "Residual Current Operated Circuit-Breakers with Integral Overcurrent Protection (RCBOs) — Part 2-1: Applicability of the General Rules to RCBOs Functionally Independent of Line Voltage", "RCBOs functionally independent of line voltage."],
    ["IS/IEC 62423:2012", "Type F and Type B Residual Current Operated Circuit-Breakers with and without Integral Overcurrent Protection for Household and Similar Uses", "Type F and B RCCBs for installations with electronic loads."],
    ["IS/IEC 60529:2013", "Degrees of Protection Provided by Enclosures (IP Code)", "IP classification of enclosures against dust and water ingress."],
    ["IS/IEC 60099-4:2014", "Surge Arresters — Part 4: Metal-Oxide Surge Arresters without Gaps for AC Systems", "Metal-oxide surge arrester requirements for AC systems."],
    ["IS/IEC 60099-5:2018", "Surge Arresters — Part 5: Selection and Application Recommendations", "Selecting and applying surge arresters."],
    ["IS/IEC 61936-1:2014", "Power Installations Exceeding 1 kV AC and 1.5 kV DC — Part 1: AC", "Design and erection requirements for high-voltage installations."],
  ],
};

const MACHINES_CABLES_AND_SOLAR: Block = {
  category: "electrical",
  rows: [
    ["IS/IEC 60034-2-2:2010", "Rotating Electrical Machines — Part 2-2: Specific Methods for Determining Separate Losses of Large Machines from Tests", "Determination of separate losses for large machines."],
    ["IS/IEC 60034-2-3:2013", "Rotating Electrical Machines — Part 2-3: Specific Test Methods for Determining Losses and Efficiency of Converter-Fed AC Motors", "Efficiency testing of converter-fed motors."],
    ["IS/IEC 60034-5:2000", "Rotating Electrical Machines — Part 5: Degrees of Protection Provided by the Integral Design of Rotating Electrical Machines", "IP classification for rotating machine enclosures."],
    ["IS/IEC 60034-6:1991", "Rotating Electrical Machines — Part 6: Methods of Cooling (IC Code)", "Cooling designation code for rotating machines."],
    ["IS/IEC 60034-7:1992", "Rotating Electrical Machines — Part 7: Classification of Types of Construction and Mounting Arrangements (IM Code)", "Mounting arrangement designation for machines."],
    ["IS/IEC 60034-8:2014", "Rotating Electrical Machines — Part 8: Terminal Markings and Direction of Rotation", "Terminal marking and rotation conventions."],
    ["IS/IEC 60034-9:2007", "Rotating Electrical Machines — Part 9: Noise Limits", "Sound power level limits for rotating machines."],
    ["IS/IEC 60034-12:2016", "Rotating Electrical Machines — Part 12: Starting Performance of Single-Speed Three-Phase Cage Induction Motors", "Starting performance characteristics for cage induction motors."],
    ["IS/IEC 60034-17:2006", "Rotating Electrical Machines — Part 17: Cage Induction Motors When Fed from Converters — Application Guide", "Application guidance for converter-fed cage motors."],
    ["IS/IEC 60034-18-1:2010", "Rotating Electrical Machines — Part 18-1: Functional Evaluation of Insulation Systems — General Guidelines", "Functional evaluation of machine insulation systems."],
    ["IS/IEC 60034-18-2:2014", "Rotating Electrical Machines — Part 18-2: Functional Evaluation of Insulation Systems — Test Procedures for Form-Wound Windings", "Test procedures for form-wound winding insulation."],
    ["IS/IEC 60034-18-31:2012", "Rotating Electrical Machines — Part 18-31: Functional Evaluation of Insulation Systems — Test Procedures for Form-Wound Windings — Thermal Evaluation and Classification of Insulation Systems Used in Machines up to and Including 50 MVA", "Thermal evaluation of form-wound insulation systems."],
    ["IS/IEC 60034-30-1:2014", "Rotating Electrical Machines — Part 30-1: Efficiency Classes of Line Operated AC Motors (IE Code)", "IE efficiency classes for line-operated AC motors."],
    ["IS/IEC 60044-1:2003", "Instrument Transformers — Part 1: Current Transformers", "Current transformer accuracy, insulation and tests."],
    ["IS/IEC 60044-2:2003", "Instrument Transformers — Part 2: Inductive Voltage Transformers", "Inductive voltage transformer requirements."],
    ["IS/IEC 60044-5:2004", "Instrument Transformers — Part 5: Capacitor Voltage Transformers", "Capacitor voltage transformer requirements."],
    ["IS/IEC 60044-7:2010", "Instrument Transformers — Part 7: Electronic Voltage Transformers", "Electronic voltage transformers for metering and protection."],
    ["IS/IEC 60044-8:2010", "Instrument Transformers — Part 8: Electronic Current Transformers", "Electronic current transformers for substation applications."],
    ["IS/IEC 60227-1:2007", "Polyvinyl Chloride Insulated Cables of Rated Voltages up to and Including 450/750 V — Part 1: General Requirements", "General requirements for PVC insulated cables.", "M", { keywords: ["cable", "pvc", "wiring", "केबल"] }],
    ["IS/IEC 60227-2:2003", "Polyvinyl Chloride Insulated Cables of Rated Voltages up to and Including 450/750 V — Part 2: Test Methods", "Test methods applicable to PVC insulated cables."],
    ["IS/IEC 60227-5:2011", "Polyvinyl Chloride Insulated Cables of Rated Voltages up to and Including 450/750 V — Part 5: Flexible Cables (Cords)", "Flexible cord construction and test requirements."],
    ["IS/IEC 60332-1-1:2015", "Tests on Electric and Optical Fibre Cables under Fire Conditions — Part 1-1: Test for Vertical Flame Propagation for a Single Insulated Wire or Cable — Apparatus", "Apparatus for single wire vertical flame propagation testing."],
    ["IS/IEC 60332-1-2:2015", "Tests on Electric and Optical Fibre Cables under Fire Conditions — Part 1-2: Test for Vertical Flame Propagation for a Single Insulated Wire or Cable — Procedure", "Procedure for single insulated wire flame propagation test."],
    ["IS/IEC 60332-3-21:2018", "Tests on Electric Cables under Fire Conditions — Part 3-21: Test for Vertical Flame Spread of Vertically-Mounted Bunched Wires or Cables — Category A F/R", "Category A F/R bunched cable flame spread test."],
    ["IS/IEC 60332-3-22:2018", "Tests on Electric Cables under Fire Conditions — Part 3-22: Test for Vertical Flame Spread of Vertically-Mounted Bunched Wires or Cables — Category A", "Category A bunched cable flame spread test."],
    ["IS/IEC 60332-3-23:2018", "Tests on Electric Cables under Fire Conditions — Part 3-23: Test for Vertical Flame Spread of Vertically-Mounted Bunched Wires or Cables — Category B", "Category B bunched cable flame spread test."],
    ["IS/IEC 60332-3-24:2018", "Tests on Electric Cables under Fire Conditions — Part 3-24: Test for Vertical Flame Spread of Vertically-Mounted Bunched Wires or Cables — Category C", "Category C bunched cable flame spread test."],
    ["IS/IEC 60332-3-25:2018", "Tests on Electric Cables under Fire Conditions — Part 3-25: Test for Vertical Flame Spread of Vertically-Mounted Bunched Wires or Cables — Category D", "Category D bunched cable flame spread test."],
    ["IS/IEC 60754-1:2014", "Test on Gases Evolved during Combustion of Materials from Cables — Part 1: Determination of the Halogen Acid Gas Content", "Halogen acid gas evolution from cable materials."],
    ["IS/IEC 60754-2:2014", "Test on Gases Evolved during Combustion of Materials from Cables — Part 2: Determination of Acidity (pH) and Conductivity", "Acidity and conductivity of evolved combustion gases."],
    ["IS/IEC 61034-1:2019", "Measurement of Smoke Density of Cables Burning under Defined Conditions — Part 1: Test Apparatus", "Smoke density test apparatus for cables."],
    ["IS/IEC 61034-2:2019", "Measurement of Smoke Density of Cables Burning under Defined Conditions — Part 2: Test Procedure and Requirements", "Smoke density test procedure and acceptance criteria."],
    ["IS/IEC 60840:2020", "Power Cables with Extruded Insulation and Their Accessories for Rated Voltages above 30 kV (Um = 36 kV) up to 150 kV (Um = 170 kV) — Test Methods and Requirements", "Type and routine tests for HV extruded insulation cables."],
    ["IS/IEC 62067:2011", "Power Cables with Extruded Insulation and Their Accessories for Rated Voltages above 150 kV (Um = 170 kV) up to 500 kV (Um = 550 kV) — Test Methods and Requirements", "Test requirements for EHV extruded insulation cables."],
    ["IS/IEC 60287-1-1:2014", "Electric Cables — Calculation of the Current Rating — Part 1-1: Current Rating Equations and Calculation of Losses", "Current rating equations and loss calculation for cables."],
    ["IS/IEC 60853-1:2002", "Calculation of the Cyclic and Emergency Current Ratings of Cables — Part 1: Cyclic Rating Factor for Cables up to and Including 18/30 (36) kV", "Cyclic rating factors for medium-voltage cables."],
    ["IS/IEC 60896-11:2017", "Stationary Lead-Acid Batteries — Part 11: Vented Types — General Requirements and Methods of Tests", "Vented stationary lead-acid battery requirements."],
    ["IS/IEC 60896-21:2014", "Stationary Lead-Acid Batteries — Part 21: Valve Regulated Types — Methods of Test", "Test methods for VRLA stationary batteries."],
    ["IS/IEC 60896-22:2014", "Stationary Lead-Acid Batteries — Part 22: Valve Regulated Types — Requirements", "Requirements for VRLA stationary battery types."],
    ["IS/IEC 62485-2:2018", "Safety Requirements for Secondary Batteries and Battery Installations — Part 2: Stationary Batteries", "Safety requirements for stationary battery installations."],
    ["IS/IEC 62485-3:2014", "Safety Requirements for Secondary Batteries and Battery Installations — Part 3: Traction Batteries", "Safety requirements for traction battery installations."],
    ["IS/IEC 62619:2017", "Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes — Safety Requirements for Secondary Lithium Cells and Batteries for Use in Industrial Applications", "Safety of industrial lithium cells and battery systems."],
    ["IS/IEC 62109-1:2010", "Safety of Power Converters for Use in Photovoltaic Power Systems — Part 1: General Requirements", "General safety requirements for PV power converters."],
    ["IS/IEC 62109-2:2011", "Safety of Power Converters for Use in Photovoltaic Power Systems — Part 2: Particular Requirements for Inverters", "Particular safety requirements for PV inverters."],
    ["IS/IEC 62116:2014", "Utility-Interconnected Photovoltaic Inverters — Test Procedure of Islanding Prevention Measures", "Anti-islanding test procedure for grid-connected inverters."],
    ["IS/IEC 61727:2004", "Photovoltaic (PV) Systems — Characteristics of the Utility Interface", "Utility interface characteristics for PV systems."],
    ["IS/IEC 62548:2016", "Photovoltaic (PV) Arrays — Design Requirements", "Design requirements for PV arrays and their wiring."],
    ["IS/IEC 62446-1:2016", "Photovoltaic (PV) Systems — Requirements for Testing, Documentation and Maintenance — Part 1: Grid Connected Systems — Documentation, Commissioning Tests and Inspection", "Commissioning tests and documentation for grid-connected PV."],
    ["IS 17017-23:2019", "Electric Vehicle Conductive Charging System — Part 23: DC Electric Vehicle Supply Equipment", "DC EV supply equipment for conductive charging."],
    ["IS 17017-24:2019", "Electric Vehicle Conductive Charging System — Part 24: Digital Communication between a DC EV Charging Station and an Electric Vehicle", "Digital communication requirements for DC charging."],
    ["IS 17017-3:2019", "Electric Vehicle Conductive Charging System — Part 3: Specific Requirements for the Connection of Electric Vehicles to a Supply Network", "Connection requirements for EV charging to the supply network."],
  ],
};

const ELECTRONICS_SAFETY_AND_EMC: Block = {
  category: "electronics",
  rows: [
    ["IS/IEC 62368-1:2018", "Audio/Video, Information and Communication Technology Equipment — Part 1: Safety Requirements", "Hazard-based safety requirements replacing separate AV and IT standards.", "C"],
    ["IS/IEC 60950-1:2011", "Information Technology Equipment — Safety — Part 1: General Requirements", "Baseline safety requirements for information technology equipment.", "C"],
    ["IS/IEC 60950-21:2003", "Information Technology Equipment — Safety — Part 21: Remote Power Feeding", "Safety requirements for remote power feeding arrangements."],
    ["IS/IEC 60950-22:2016", "Information Technology Equipment — Safety — Part 22: Equipment to Be Installed Outdoors", "Outdoor-installed IT equipment safety requirements."],
    ["IS/IEC 60950-23:2006", "Information Technology Equipment — Safety — Part 23: Large Data Storage Equipment", "Safety requirements for large data storage equipment."],
    ["IS/IEC 60065:2014", "Audio, Video and Similar Electronic Apparatus — Safety Requirements", "Safety requirements for consumer audio and video apparatus."],
    ["IS/IEC 62031:2018", "LED Modules for General Lighting — Safety Specifications", "Safety specifications for LED modules.", "C"],
    ["IS/IEC 62560:2011", "Self-Ballasted LED-Lamps for General Lighting Services by Voltage > 50 V — Safety Specifications", "Safety specifications for self-ballasted LED lamps.", "C"],
    ["IS/IEC 62612:2015", "Self-Ballasted LED-Lamps for General Lighting Services with Supply Voltages > 50 V — Performance Requirements", "Performance requirements for self-ballasted LED lamps."],
    ["IS/IEC 60968:2015", "Self-Ballasted Fluorescent Lamps for General Lighting Services — Safety Requirements", "Safety requirements for self-ballasted fluorescent lamps.", "C"],
    ["IS/IEC 60969:2016", "Self-Ballasted Fluorescent Lamps for General Lighting Services — Performance Requirements", "Performance requirements for CFL lamps."],
    ["IS/IEC 61195:2014", "Double-Capped Fluorescent Lamps — Safety Specifications", "Safety specifications for double-capped fluorescent lamps."],
    ["IS/IEC 61199:2014", "Single-Capped Fluorescent Lamps — Safety Specifications", "Safety specifications for single-capped fluorescent lamps."],
    ["IS/IEC 60081:2017", "Double-Capped Fluorescent Lamps — Performance Specifications", "Performance specifications for tubular fluorescent lamps."],
    ["IS/IEC 62471:2008", "Photobiological Safety of Lamps and Lamp Systems", "Blue light and UV hazard classification for lamps."],
    ["IS/IEC 60825-1:2014", "Safety of Laser Products — Part 1: Equipment Classification and Requirements", "Laser product classification and safety requirements."],
    ["IS/IEC 60825-2:2010", "Safety of Laser Products — Part 2: Safety of Optical Fibre Communication Systems", "Safety of optical fibre communication systems."],
    ["IS/IEC 60825-4:2017", "Safety of Laser Products — Part 4: Laser Guards", "Laser guard requirements and testing."],
    ["IS/IEC 60825-12:2016", "Safety of Laser Products — Part 12: Safety of Free Space Optical Communication Systems Used for Transmission of Information", "Free space optical communication system safety."],
    ["IS/IEC 61340-5-1:2016", "Electrostatics — Part 5-1: Protection of Electronic Devices from Electrostatic Phenomena — General Requirements", "ESD control programme requirements for electronic devices."],
    ["IS/IEC 61340-4-1:2003", "Electrostatics — Part 4-1: Standard Test Methods for Specific Applications — Electrical Resistance of Floor Coverings and Installed Floors", "Resistance testing of ESD flooring."],
    ["IS/IEC 60068-1:2013", "Environmental Testing — Part 1: General and Guidance", "General guidance for environmental test programmes."],
    ["IS/IEC 60068-2-1:2007", "Environmental Testing — Part 2-1: Tests — Test A: Cold", "Cold test for components and equipment."],
    ["IS/IEC 60068-2-2:2007", "Environmental Testing — Part 2-2: Tests — Test B: Dry Heat", "Dry heat test procedures."],
    ["IS/IEC 60068-2-5:2018", "Environmental Testing — Part 2-5: Tests — Test S: Simulated Solar Radiation at Ground Level and Guidance for Solar Radiation Testing", "Simulated solar radiation testing."],
    ["IS/IEC 60068-2-6:2007", "Environmental Testing — Part 2-6: Tests — Test Fc: Vibration (Sinusoidal)", "Sinusoidal vibration test procedures."],
    ["IS/IEC 60068-2-11:2021", "Environmental Testing — Part 2-11: Tests — Test Ka: Salt Mist", "Salt mist corrosion testing."],
    ["IS/IEC 60068-2-13:2021", "Environmental Testing — Part 2-13: Tests — Test M: Low Air Pressure", "Low air pressure testing."],
    ["IS/IEC 60068-2-14:2009", "Environmental Testing — Part 2-14: Tests — Test N: Change of Temperature", "Temperature cycling test procedures."],
    ["IS/IEC 60068-2-27:2008", "Environmental Testing — Part 2-27: Tests — Test Ea and Guidance: Shock", "Shock test procedures and guidance."],
    ["IS/IEC 60068-2-30:2005", "Environmental Testing — Part 2-30: Tests — Test Db: Damp Heat, Cyclic", "Cyclic damp heat testing."],
    ["IS/IEC 60068-2-38:2021", "Environmental Testing — Part 2-38: Tests — Test Z/AD: Composite Temperature/Humidity Cyclic Test", "Composite temperature and humidity cycling test."],
    ["IS/IEC 60068-2-52:2017", "Environmental Testing — Part 2-52: Tests — Test Kb: Salt Mist, Cyclic (Sodium Chloride Solution)", "Cyclic salt mist testing."],
    ["IS/IEC 60068-2-64:2008", "Environmental Testing — Part 2-64: Tests — Test Fh: Vibration, Broadband Random and Guidance", "Random vibration testing and guidance."],
    ["IS/IEC 60068-2-78:2012", "Environmental Testing — Part 2-78: Tests — Test Cab: Damp Heat, Steady State", "Steady-state damp heat testing."],
    ["IS/IEC 60695-1-10:2016", "Fire Hazard Testing — Part 1-10: Guidance for Assessing the Fire Hazard of Electrotechnical Products — General Guidelines", "General guidance for fire hazard assessment."],
    ["IS/IEC 60695-1-11:2014", "Fire Hazard Testing — Part 1-11: Guidance for Assessing the Fire Hazard of Electrotechnical Products — Fire Hazard Assessment", "Fire hazard assessment methodology."],
    ["IS/IEC 60695-2-1:2014", "Fire Hazard Testing — Part 2-1: Glowing/Hot-Wire Based Test Methods — Glow-Wire Apparatus and Common Test Procedure", "Glow-wire apparatus and common test procedure."],
    ["IS/IEC 60695-2-10:2013", "Fire Hazard Testing — Part 2-10: Glowing/Hot-Wire Based Test Methods — Glow-Wire Apparatus and Common Test Procedure", "Glow-wire test apparatus and procedure."],
    ["IS/IEC 60695-2-11:2014", "Fire Hazard Testing — Part 2-11: Glowing/Hot-Wire Based Test Methods — Glow-Wire Flammability Test Method for End-Products (GWEPT)", "Glow-wire flammability test for end products."],
    ["IS/IEC 60695-2-12:2014", "Fire Hazard Testing — Part 2-12: Glowing/Hot-Wire Based Test Methods — Glow-Wire Flammability Test Method for Materials", "Glow-wire flammability test for materials."],
    ["IS/IEC 60695-2-13:2014", "Fire Hazard Testing — Part 2-13: Glowing/Hot-Wire Based Test Methods — Glow-Wire Ignition Temperature (GWIT) Test Method for Materials", "Glow-wire ignition temperature determination."],
    ["IS/IEC 60695-10-2:2014", "Fire Hazard Testing — Part 10-2: Abnormal Heat — Ball Pressure Test Method", "Ball pressure test for material softening."],
    ["IS/IEC 60695-10-3:2016", "Fire Hazard Testing — Part 10-3: Abnormal Heat — Mould Stress Relief Distortion Test", "Mould stress relief distortion testing."],
    ["IS/IEC 60695-11-10:2013", "Fire Hazard Testing — Part 11-10: Test Flames — 50 W Horizontal and Vertical Flame Test Methods", "50 W horizontal and vertical flame test methods."],
    ["IS/IEC 60695-11-20:2015", "Fire Hazard Testing — Part 11-20: Test Flames — 500 W Flame Test Methods", "500 W flame test methods for materials."],
    ["IS 14700-3-11:2016", "Electromagnetic Compatibility — Part 3-11: Limits — Limitation of Voltage Changes, Voltage Fluctuations and Flicker in Public Low-Voltage Supply Systems", "Flicker emission limits for equipment rated up to 75 A."],
    ["IS 14700-3-12:2016", "Electromagnetic Compatibility — Part 3-12: Limits — Limits for Harmonic Currents Produced by Equipment Connected to Public Low-Voltage Systems with Input Current Greater than 16 A and Less than or Equal to 75 A per Phase", "Harmonic current limits for larger connected equipment."],
    ["IS 14700-4-19:2019", "Electromagnetic Compatibility — Part 4-19: Testing and Measurement Techniques — Test for Immunity to Conducted, Differential Mode Disturbances and Signalling in the Frequency Range 2 kHz to 150 kHz at AC Power Ports", "Immunity testing below 150 kHz at AC power ports."],
    ["IS 14700-4-26:2019", "Electromagnetic Compatibility — Part 4-26: Testing and Measurement Techniques — Immunity to Conducted Disturbances at Frequencies above 9 kHz and up to 150 kHz at Power Ports", "High-frequency conducted disturbance immunity."],
    ["IS 14700-4-31:2019", "Electromagnetic Compatibility — Part 4-31: Testing and Measurement Techniques — AC Mains Ports Conducted Disturbance Immunity Test in the Frequency Range 150 kHz to 80 MHz", "Mains port conducted immunity testing."],
    ["IS 14700-4-33:2019", "Electromagnetic Compatibility — Part 4-33: Testing and Measurement Techniques — Measurement Methods for High-Power Transient Parameters", "High-power transient parameter measurement methods."],
    ["IS 14700-4-39:2019", "Electromagnetic Compatibility — Part 4-39: Testing and Measurement Techniques — Radiated Fields in Close Proximity — Immunity Test", "Immunity to radiated fields in close proximity."],
    ["IS 14700-6-5:2019", "Electromagnetic Compatibility — Part 6-5: Generic Standards — Immunity for Equipment Used in Power Station and Substation Environment", "Immunity in power station and substation environments."],
  ],
};

export const STD_WAVE18 = buildBlocks(
  TRANSFORMERS_AND_SWITCHGEAR,
  MACHINES_CABLES_AND_SOLAR,
  ELECTRONICS_SAFETY_AND_EMC,
);
