/* Extra catalogue wave 22 — construction: geotechnical site investigation,
 * natural building stone, ceramic and gypsum products, bituminous road
 * materials, sewerage and drainage practice, tower and pile work, plus the
 * IEC-adopted rules for electrical installations in buildings and lightning
 * protection components. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const GEOTECHNICAL: Block = {
  category: "construction",
  rows: [
    ["IS 2720-3-2:1980", "Methods of Test for Soils — Part 3: Determination of Specific Gravity — Section 2: Fine, Medium and Coarse Grained Soils", "Specific gravity determination for the full range of soil gradings."],
    ["IS 2720-9:1991", "Methods of Test for Soils — Part 9: Determination of Dry Density-Moisture Content Relationship (Vibrating Hammer Method)", "Compaction curve determination using a vibrating hammer."],
    ["IS 2720-18:1992", "Methods of Test for Soils — Part 18: Determination of Residual Shear Strength", "Residual shear strength by repeated direct shear testing."],
    ["IS 2720-33:1992", "Methods of Test for Soils — Part 33: Determination of Relative Density of Cohesionless Soils", "Maximum and minimum density determination for sands."],
    ["IS 2720-34:1995", "Methods of Test for Soils — Part 34: Determination of Erodibility of Soils", "Erodibility assessment for canal and embankment design."],
    ["IS 2720-35:1995", "Methods of Test for Soils — Part 35: Determination of Swelling Pressure of Soils", "Swelling pressure measurement for expansive soils."],
    ["IS 2720-39:1995", "Methods of Test for Soils — Part 39: Determination of Swell Pressure after Saturation", "Swell pressure of compacted specimens after full saturation."],
    ["IS 2720-40:1995", "Methods of Test for Soils — Part 40: Determination of Free Swell Index of Soils", "Free swell index for classification of expansive soils."],
    ["IS 2720-41:1995", "Methods of Test for Soils — Part 41: Measurement of Swelling Pressure of Soils by the Constant Volume Method", "Constant volume swelling pressure measurement."],
    ["IS 4968-1:1976", "Method of Test for Determination of Angle of Shearing Resistance of Soils — Part 1: Laboratory Determination", "Laboratory determination of the angle of shearing resistance."],
    ["IS 8009-2:1980", "Method of Test for Settlement of Foundations — Part 2: Field Test", "Field settlement measurement for shallow foundations."],
    ["IS 1888-2:1982", "Method of Load Test on Soils — Part 2: Standard Penetration Test", "Standard penetration test procedure and corrections."],
    ["IS 1892-2:2021", "Code of Practice for Subsurface Investigation for Foundations — Part 2: Sampling and Reporting", "Borehole sampling, classification and investigation reporting."],
    ["IS 2911-1-2:2010", "Design and Construction of Pile Foundations — Part 1: Concrete Piles — Section 2: Bored Cast In-Situ Concrete Piles", "Design and construction rules for bored cast in-situ piles."],
    ["IS 2950-2:1982", "Code of Practice for Design and Construction of Raft Foundations — Part 2: Rafts for Structures on Non-Uniform Soils", "Raft design where soil properties vary across the footprint."],
    ["IS 9451-2:1994", "Code of Practice for Design and Construction of Diaphragm Walls — Part 2: Construction and Testing", "Slurry trench construction and integrity testing of diaphragm walls."],
    ["IS 14621-2:1998", "Criteria for Design of Ground Improvement — Part 2: Stone Columns", "Design criteria for stone column ground improvement."],
    ["IS 13094-2:1992", "Code of Practice for Design, Manufacture, Erection and Testing of Precast Concrete Elements — Part 2: Testing of Precast Elements", "Load testing of precast concrete elements."],
  ],
};

const STONE_TILES_AND_GYPSUM: Block = {
  category: "construction",
  rows: [
    ["IS 1121-2:1974", "Methods of Test for Determination of Strength Properties of Natural Building Stones — Part 2: Shear Strength", "Shear strength determination on stone cubes."],
    ["IS 1123:1974", "Method for Identification of Natural Building Stones", "Petrographic and physical identification of building stones."],
    ["IS 1125:1974", "Method of Test for Determination of Weathering of Natural Building Stones", "Weathering resistance by crystallization and thermal cycling."],
    ["IS 1706:1974", "Method for Determination of Resistance to Abrasion of Natural Building Stones", "Abrasion resistance by attrition testing."],
    ["IS 3316:1974", "Specification for Structural Granite", "Granite grades for structural and cladding use."],
    ["IS 6250:1981", "Specification for Roofing Slate", "Roofing slate size, thickness and water absorption limits."],
    ["IS 13630-4:2019", "Ceramic Tiles — Methods of Test, Sampling and Basis for Acceptance — Part 4: Determination of Flexural Strength (Modulus of Rupture)", "Modulus of rupture determination for ceramic tiles."],
    ["IS 13630-5:2019", "Ceramic Tiles — Methods of Test — Part 5: Determination of Impact Resistance by Measurement of Coefficient of Restitution", "Coefficient of restitution based impact resistance testing."],
    ["IS 13630-7:2019", "Ceramic Tiles — Methods of Test — Part 7: Determination of Surface Quality", "Surface defect assessment for glazed and unglazed tiles."],
    ["IS 13630-9:2019", "Ceramic Tiles — Methods of Test — Part 9: Determination of Thermal Shock Resistance", "Thermal shock resistance for glazed tiles."],
    ["IS 13630-10:2019", "Ceramic Tiles — Methods of Test — Part 10: Determination of Frost Resistance", "Frost resistance for exterior tiles."],
    ["IS 13630-12:2019", "Ceramic Tiles — Methods of Test — Part 12: Determination of Resistance to Staining", "Stain resistance classification for glazed tiles."],
    ["IS 13630-14:2019", "Ceramic Tiles — Methods of Test — Part 14: Determination of Lead and Cadmium Release", "Lead and cadmium release limits for tile surfaces."],
    ["IS 15622-1:2017", "Ceramic Tiles — Specification — Part 1: Dry Pressed Ceramic Tiles", "Classification, dimensions and marking of dry pressed tiles.", "M", { keywords: ["tiles", "ceramic", "टाइल"] }],
    ["IS 2542-2:1981", "Method of Test for Gypsum Plaster, Concrete and Products — Part 2: Determination of Compressive Strength", "Compressive strength determination for gypsum products."],
    ["IS 2542-3:1978", "Method of Test for Gypsum Plaster, Concrete and Products — Part 3: Determination of Setting Time", "Setting time determination for gypsum plasters."],
    ["IS 2542-4:1978", "Method of Test for Gypsum Plaster, Concrete and Products — Part 4: Determination of Unit Weight and Density", "Bulk density and unit weight of gypsum products."],
    ["IS 2542-5:1981", "Method of Test for Gypsum Plaster, Concrete and Products — Part 5: Determination of Water Retention", "Water retention capacity of gypsum plasters."],
    ["IS 2095-2:2013", "Gypsum Plaster Boards — Part 2: Coated and Laminated Boards — Specification", "Coated, laminated and pre-decorated gypsum board requirements."],
    ["IS 2095-3:2013", "Gypsum Plaster Boards — Part 3: Test Methods", "Test methods for gypsum plaster board performance."],
    ["IS 8272:2019", "Gypsum Plaster, Calcined — Specification", "Calcined gypsum plaster grades, fineness and setting time."],
    ["IS 12654:2019", "Gypsum Board Systems — Code of Practice for Installation", "Fixing, framing and finishing practice for gypsum board systems."],
    ["IS 6932-2:1973", "Methods of Test for Building Limes — Part 2: Determination of Soundness", "Soundness testing of building limes."],
  ],
};

const CONCRETE_AND_ROADS: Block = {
  category: "construction",
  rows: [
    ["IS 1199-2:2018", "Fresh Concrete — Methods of Sampling, Testing and Analysis — Part 2: Determination of Consistency of Fresh Concrete", "Consistency measurement including slump and flow tests."],
    ["IS 1199-3:2018", "Fresh Concrete — Methods of Sampling, Testing and Analysis — Part 3: Determination of Density of Fresh Concrete", "Density of fresh concrete and its air content calculation."],
    ["IS 1199-4:2018", "Fresh Concrete — Methods of Sampling, Testing and Analysis — Part 4: Determination of Setting Time of Concrete by Penetration Resistance", "Setting time determination by penetration resistance."],
    ["IS 4031-18:1988", "Methods of Physical Tests for Hydraulic Cement — Part 18: Determination of Alkali Content", "Alkali content determination for cement by flame photometry."],
    ["IS 4031-19:1988", "Methods of Physical Tests for Hydraulic Cement — Part 19: Determination of Sulphate Content", "Sulphate content determination for hydraulic cements."],
    ["IS 516-2:2021", "Methods of Tests for Strength of Concrete — Part 2: Determination of Flexural Strength", "Flexural strength testing of concrete beams."],
    ["IS 5816-2:2021", "Splitting Tensile Strength of Concrete — Part 2: Test Method for Cylindrical Specimens", "Splitting tensile strength using cylindrical specimens."],
    ["IS 2185-4:2008", "Concrete Masonry Units — Part 4: Autoclaved Cellular Concrete Blocks — Specification", "AAC block density, strength and drying shrinkage requirements."],
    ["IS 1077-2:2023", "Common Burnt Clay Building Bricks — Part 2: Methods of Test", "Test methods for burnt clay building bricks."],
    ["IS 1202:1978", "Methods of Testing Tar and Bituminous Materials — Part 2: Determination of Specific Gravity", "Specific gravity of tars and bituminous materials."],
    ["IS 1206-1:1978", "Methods of Testing Tar and Bituminous Materials — Part 1: Determination of Penetration", "Penetration grading of bitumen."],
    ["IS 1208:1978", "Methods of Testing Tar and Bituminous Materials — Part 8: Determination of Softening Point", "Ring and ball softening point determination."],
    ["IS 1210:1978", "Methods of Testing Tar and Bituminous Materials — Part 10: Determination of Loss on Heating", "Loss on heating test for bitumen."],
    ["IS 1211:1978", "Methods of Testing Tar and Bituminous Materials — Part 11: Determination of Flash Point", "Flash point determination for cutback bitumen."],
    ["IS 1212:1978", "Methods of Testing Tar and Bituminous Materials — Part 12: Determination of Solubility in Carbon Disulphide", "Solubility of bitumen in carbon disulphide."],
    ["IS 1216:1978", "Methods of Testing Tar and Bituminous Materials — Part 16: Determination of Ductility", "Ductility test for bituminous binders."],
    ["IS 15462:2019", "Polymer and Rubber Modified Bitumen — Specification", "Modified bitumen grades for road construction.", "M", { keywords: ["bitumen", "road", "polymer modified"] }],
    ["IS 15658-2:2019", "Precast Concrete Blocks for Paving — Part 2: Test Methods", "Test methods for precast concrete paving blocks."],
    ["IS 383-2:2016", "Coarse and Fine Aggregate for Concrete — Part 2: Methods of Sampling and Testing", "Sampling and testing of concrete aggregates."],
    ["IS 2116-2:2020", "Sand for Masonry Mortars — Part 2: Methods of Test", "Testing of sand for masonry mortars."],
  ],
};

const DRAINAGE_WATER_AND_MISC: Block = {
  category: "construction",
  rows: [
    ["IS 4111-1:2020", "Code of Practice for Laying of Sewers and Water Mains — Part 1: Planning and Design", "Planning, alignment and design of sewer and water main networks."],
    ["IS 4111-2:2020", "Code of Practice for Laying of Sewers and Water Mains — Part 2: Excavation, Bedding and Jointing", "Trenching, bedding, jointing and backfilling practice."],
    ["IS 4111-3:2020", "Code of Practice for Laying of Sewers and Water Mains — Part 3: Testing and Commissioning", "Air, water and infiltration testing before commissioning."],
    ["IS 2470-3:1985", "Code of Practice for Installation of Septic Tanks — Part 3: Secondary Treatment Units", "Up-flow filters and secondary treatment after septic tanks."],
    ["IS 15797:2008", "Roof Top Rainwater Harvesting — Guidelines", "Design, filtration and storage guidance for rooftop rainwater harvesting."],
    ["IS 7894:1975", "Code of Practice for Stability Analysis of Earth Dams", "Slope stability analysis methods for earth dams."],
    ["IS 12169:1987", "Criteria for Design of Small Embankment Dams", "Design criteria for small embankment dams and their appurtenances."],
    ["IS 802-2:2015", "Code of Practice for Use of Structural Steel in Overhead Transmission Line Towers — Part 2: Fabrication, Galvanizing and Erection", "Fabrication, galvanizing and erection of transmission towers."],
    ["IS 802-3:2017", "Code of Practice for Use of Structural Steel in Overhead Transmission Line Towers — Part 3: Testing of Towers", "Full-scale tower testing and strain measurement."],
    ["IS 1080:2021", "Design and Construction of Shallow Foundations — Code of Practice", "Design and construction of shallow foundations in soils."],
    ["IS 6313-3:2018", "Code of Practice for Anti-Termite Measures in Buildings — Part 3: Chemical Treatment for Masonry and Wood", "Pre-construction and post-construction anti-termite treatment."],
    ["IS 3594:2019", "Code of Practice for Fire Safety of Industrial Buildings — General Storage and Warehousing", "Fire safety provisions for warehouses and storage buildings."],
    ["IS 1642-2:2020", "Fire Safety of Buildings (General): Details of Construction — Part 2: Openings and Shafts", "Protection of openings, shafts and vertical communication."],
    ["IS 12335:2019", "Code of Practice for Waterproofing of Underground Structures", "Waterproofing systems and detailing below ground level."],
    ["IS 3067-2:2020", "Code of Practice for Damp-Proofing of Buildings — Part 2: Materials and Application", "Damp-proof course materials, membranes and application."],
    ["IS 2394:2019", "Code of Practice for Painting of Concrete and Masonry Surfaces", "Surface preparation, priming and painting of concrete and masonry."],
    ["IS 1477-1:2019", "Code of Practice for Painting of Ferrous Metals in Buildings — Part 1: Pre-treatment", "Surface preparation of ferrous metal before painting."],
    ["IS 1477-2:2019", "Code of Practice for Painting of Ferrous Metals in Buildings — Part 2: Painting", "Paint systems for structural and architectural steelwork."],
    ["IS 6278:2020", "Code of Practice for White Washing and Colour Washing", "Lime wash and colour wash preparation and application."],
    ["IS 15884-2:2020", "Alternating Current Direct Connected Static Prepayment Meters for Active Energy — Part 2: Testing and Verification", "Verification tests for prepayment energy meters."],
  ],
};

const BUILDING_SERVICES_IEC: Block = {
  category: "construction",
  rows: [
    ["IS/IEC 60364-1:2019", "Low-Voltage Electrical Installations — Part 1: Fundamental Principles, Assessment of General Characteristics, Definitions", "Fundamental safety principles for low-voltage installations in buildings."],
    ["IS/IEC 60364-4-41:2020", "Low-Voltage Electrical Installations — Part 4-41: Protection for Safety — Protection against Electric Shock", "Protection against electric shock by automatic disconnection and double insulation."],
    ["IS/IEC 60364-4-42:2019", "Low-Voltage Electrical Installations — Part 4-42: Protection for Safety — Protection against Thermal Effects", "Protection of persons and property against thermal effects."],
    ["IS/IEC 60364-4-43:2020", "Low-Voltage Electrical Installations — Part 4-43: Protection for Safety — Protection against Overcurrent", "Overcurrent protection co-ordination for circuits and equipment."],
    ["IS/IEC 60364-4-44:2019", "Low-Voltage Electrical Installations — Part 4-44: Protection for Safety — Protection against Voltage Disturbances and Electromagnetic Disturbances", "Protection against voltage and electromagnetic disturbances."],
    ["IS/IEC 60364-5-52:2019", "Low-Voltage Electrical Installations — Part 5-52: Selection and Erection of Electrical Equipment — Wiring Systems", "Current-carrying capacity, installation methods and wiring systems."],
    ["IS/IEC 60364-5-54:2019", "Low-Voltage Electrical Installations — Part 5-54: Selection and Erection of Electrical Equipment — Earthing Arrangements, Protective Conductors and Protective Bonding Conductors", "Earthing and protective bonding conductor requirements."],
    ["IS/IEC 60364-6:2019", "Low-Voltage Electrical Installations — Part 6: Verification", "Initial verification and periodic inspection of installations."],
    ["IS/IEC 60364-7-701:2019", "Low-Voltage Electrical Installations — Part 7-701: Requirements for Special Installations or Locations — Locations Containing a Bath Tub or Shower Basin", "Electrical safety requirements for bathrooms and shower areas."],
    ["IS/IEC 60364-7-702:2019", "Low-Voltage Electrical Installations — Part 7-702: Requirements for Special Installations or Locations — Swimming Pools and Fountains", "Electrical installation rules for pools and fountains."],
    ["IS/IEC 60364-7-703:2019", "Low-Voltage Electrical Installations — Part 7-703: Requirements for Special Installations or Locations — Rooms and Cabins Containing Sauna Heaters", "Wiring rules for sauna rooms and cabins."],
    ["IS/IEC 60364-7-704:2019", "Low-Voltage Electrical Installations — Part 7-704: Requirements for Special Installations or Locations — Construction and Demolition Site Installations", "Temporary installations on construction and demolition sites."],
    ["IS/IEC 60364-7-705:2019", "Low-Voltage Electrical Installations — Part 7-705: Requirements for Special Installations or Locations — Agricultural and Horticultural Premises", "Installations in agricultural and horticultural premises."],
    ["IS/IEC 60364-7-706:2019", "Low-Voltage Electrical Installations — Part 7-706: Requirements for Special Installations or Locations — Conducting Locations with Restricted Movement", "Wiring in conductive locations with restricted movement."],
    ["IS/IEC 60364-7-708:2019", "Low-Voltage Electrical Installations — Part 7-708: Requirements for Special Installations or Locations — Caravan Parks, Camping Parks and Similar Locations", "Distribution and protection in caravan and camping parks."],
    ["IS/IEC 60364-7-709:2019", "Low-Voltage Electrical Installations — Part 7-709: Requirements for Special Installations or Locations — Marinas and Similar Locations", "Installations in marinas and similar locations."],
    ["IS/IEC 60364-7-710:2019", "Low-Voltage Electrical Installations — Part 7-710: Requirements for Special Installations or Locations — Medical Locations", "Electrical safety requirements for medical locations and hospital areas."],
    ["IS/IEC 60364-7-711:2019", "Low-Voltage Electrical Installations — Part 7-711: Requirements for Special Installations or Locations — Exhibitions, Shows and Stands", "Temporary installations for exhibitions and stands."],
    ["IS/IEC 60364-7-712:2019", "Low-Voltage Electrical Installations — Part 7-712: Requirements for Special Installations or Locations — Solar Photovoltaic (PV) Power Supply Systems", "Wiring rules for rooftop and building-integrated PV systems."],
    ["IS/IEC 60364-7-713:2019", "Low-Voltage Electrical Installations — Part 7-713: Requirements for Special Installations or Locations — Furniture", "Electrical installation rules for furniture with built-in power."],
    ["IS/IEC 60364-7-714:2019", "Low-Voltage Electrical Installations — Part 7-714: Requirements for Special Installations or Locations — External Lighting Installations", "External lighting circuits and protection."],
    ["IS/IEC 60364-7-715:2019", "Low-Voltage Electrical Installations — Part 7-715: Requirements for Special Installations or Locations — Extra-Low-Voltage Lighting Installations", "Extra-low-voltage lighting installation rules."],
    ["IS/IEC 60364-7-717:2019", "Low-Voltage Electrical Installations — Part 7-717: Requirements for Special Installations or Locations — Mobile or Transportable Units", "Installations in mobile and transportable units."],
    ["IS/IEC 60364-7-718:2019", "Low-Voltage Electrical Installations — Part 7-718: Requirements for Special Installations or Locations — Communal Facilities and Workplaces", "Installations in communal facilities and workplaces."],
    ["IS/IEC 60364-7-721:2019", "Low-Voltage Electrical Installations — Part 7-721: Requirements for Special Installations or Locations — Electrical Installations in Caravans and Motor Caravans", "Low-voltage installations in caravans and motor caravans."],
    ["IS/IEC 60364-7-722:2019", "Low-Voltage Electrical Installations — Part 7-722: Requirements for Special Installations or Locations — Supplies for Electric Vehicles", "Supply installations for electric vehicle charging points."],
    ["IS/IEC 60364-7-729:2019", "Low-Voltage Electrical Installations — Part 7-729: Requirements for Special Installations or Locations — Operating or Maintenance Gangways", "Clearance and access requirements for switchgear gangways."],
    ["IS/IEC 60364-7-740:2019", "Low-Voltage Electrical Installations — Part 7-740: Requirements for Special Installations or Locations — Temporary Electrical Installations for Structures, Amusement Devices and Booths at Fairgrounds, Amusement Parks and Circuses", "Temporary installations for fairs and amusement parks."],
    ["IS/IEC 60364-8-1:2019", "Low-Voltage Electrical Installations — Part 8-1: Functional Aspects — Energy Efficiency", "Energy efficiency assessment and design of building installations."],
    ["IS/IEC 62305-3:2012", "Protection against Lightning — Part 3: Physical Damage to Structures and Life Hazard", "Air termination, down conductor and earthing design for structures."],
    ["IS/IEC 62305-4:2012", "Protection against Lightning — Part 4: Electrical and Electronic Systems within Structures", "Surge protection of electrical and electronic systems in buildings."],
    ["IS/IEC 62561-1:2017", "Lightning Protection System Components (LPSC) — Part 1: Requirements for Connection Components", "Connection component requirements for lightning protection systems."],
    ["IS/IEC 62561-2:2018", "Lightning Protection System Components (LPSC) — Part 2: Requirements for Conductors and Earth Electrodes", "Conductor and earth electrode requirements for lightning protection."],
    ["IS/IEC 62561-3:2017", "Lightning Protection System Components (LPSC) — Part 3: Requirements for Isolating Spark Gaps", "Isolating spark gap requirements and testing."],
    ["IS/IEC 62561-4:2017", "Lightning Protection System Components (LPSC) — Part 4: Requirements for Conductor Fasteners", "Conductor fastener mechanical and corrosion requirements."],
    ["IS/IEC 62561-7:2018", "Lightning Protection System Components (LPSC) — Part 7: Requirements for Earthing Enhancing Compounds", "Earthing enhancing compound requirements and test methods."],
  ],
};

export const STD_WAVE22 = buildBlocks(
  GEOTECHNICAL,
  STONE_TILES_AND_GYPSUM,
  CONCRETE_AND_ROADS,
  DRAINAGE_WATER_AND_MISC,
  BUILDING_SERVICES_IEC,
);
