/* Extra catalogue wave 23 — food safety analysis (ISO-adopted microbiology and
 * chemistry methods), household consumer products and the remaining service
 * sector adoptions (supply-chain security, emergency management, laboratory
 * medicine and IT governance). */
import { buildBlocks, type Block } from "@/db/seed-kit";

const FOOD_MICROBIOLOGY: Block = {
  category: "food",
  rows: [
    ["IS/ISO 6579-2:2017", "Microbiology of the Food Chain — Horizontal Method for the Detection, Enumeration and Serotyping of Salmonella — Part 2: Enumeration by a Miniaturized Most Probable Number Technique", "MPN enumeration of Salmonella in food and feed."],
    ["IS/ISO 6579-3:2014", "Microbiology of the Food Chain — Horizontal Method for the Detection, Enumeration and Serotyping of Salmonella — Part 3: Guidelines for Serotyping of Salmonella spp.", "Serotyping guidance for Salmonella isolates."],
    ["IS/ISO 6887-1:2017", "Microbiology of the Food Chain — Preparation of Test Samples, Initial Suspension and Decimal Dilutions for Microbiological Examination — Part 1: General Rules for the Preparation of the Initial Suspension and Decimal Dilutions", "General rules for test sample preparation and dilution."],
    ["IS/ISO 6887-2:2017", "Microbiology of the Food Chain — Preparation of Test Samples, Initial Suspension and Decimal Dilutions — Part 2: Specific Rules for the Preparation of Meat and Meat Products", "Sample preparation for meat and meat products."],
    ["IS/ISO 6887-3:2017", "Microbiology of the Food Chain — Preparation of Test Samples, Initial Suspension and Decimal Dilutions — Part 3: Specific Rules for the Preparation of Fish and Fishery Products", "Sample preparation for fish and fishery products."],
    ["IS/ISO 6887-4:2017", "Microbiology of the Food Chain — Preparation of Test Samples, Initial Suspension and Decimal Dilutions — Part 4: Specific Rules for the Preparation of Miscellaneous Products", "Sample preparation for miscellaneous food commodities."],
    ["IS/ISO 6887-5:2020", "Microbiology of the Food Chain — Preparation of Test Samples, Initial Suspension and Decimal Dilutions — Part 5: Specific Rules for the Preparation of Milk and Milk Products", "Sample preparation for milk and milk products."],
    ["IS/ISO 6887-6:2013", "Microbiology of Food and Animal Feed — Preparation of Test Samples, Initial Suspension and Decimal Dilutions — Part 6: Specific Rules for the Preparation of Samples Taken at the Primary Production Stage", "Primary production stage sample preparation."],
    ["IS/ISO 7218:2013", "Microbiology of Food and Animal Feeding Stuffs — General Requirements and Guidance for Microbiological Examinations", "General laboratory requirements and examination guidance."],
    ["IS/ISO 4831:2006", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Detection and Enumeration of Coliforms — Most Probable Number Technique", "Coliform MPN detection and enumeration."],
    ["IS/ISO 4832:2006", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Coliforms — Colony-Count Technique", "Coliform colony count technique."],
    ["IS/ISO 7954:1987", "Microbiology — General Guidance for Enumeration of Yeasts and Moulds — Colony Count Technique at 25 °C", "Yeast and mould enumeration by colony count."],
    ["IS/ISO 16654:2001", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Detection of Escherichia coli O157", "Detection of E. coli O157 in food and feed."],
    ["IS/ISO 16649-1:2018", "Microbiology of the Food Chain — Horizontal Method for the Enumeration of Beta-Glucuronidase-Positive Escherichia coli — Part 1: Colony-Count Technique at 44 °C Using Membranes and 5-Bromo-4-Chloro-3-Indolyl Beta-D-Glucuronide", "Membrane colony count for beta-glucuronidase-positive E. coli."],
    ["IS/ISO 16649-3:2015", "Microbiology of the Food Chain — Horizontal Method for the Enumeration of Beta-Glucuronidase-Positive Escherichia coli — Part 3: Detection and Most Probable Number Technique Using 5-Bromo-4-Chloro-3-Indolyl-Beta-D-Glucuronide", "MPN detection of beta-glucuronidase-positive E. coli."],
    ["IS/ISO 21528-1:2017", "Microbiology of the Food Chain — Horizontal Method for the Detection and Enumeration of Enterobacteriaceae — Part 1: Detection of Enterobacteriaceae", "Detection of Enterobacteriaceae in food products."],
    ["IS/ISO 21528-2:2017", "Microbiology of the Food Chain — Horizontal Method for the Detection and Enumeration of Enterobacteriaceae — Part 2: Colony-Count Technique", "Enterobacteriaceae colony count technique."],
    ["IS/ISO 10272-2:2017", "Microbiology of the Food Chain — Horizontal Method for Detection and Enumeration of Campylobacter spp. — Part 2: Colony-Count Technique", "Campylobacter colony count technique."],
    ["IS/ISO 17604:2015", "Microbiology of the Food Chain — Carcass Sampling for Microbiological Analysis", "Carcass sampling plans for microbiological analysis."],
    ["IS/ISO 15213:2003", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Sulfite-Reducing Bacteria Growing under Anaerobic Conditions", "Sulphite-reducing clostridia enumeration."],
    ["IS/ISO 7932:2004", "Microbiology of Food and Animal Feeding Stuffs — Horizontal Method for the Enumeration of Presumptive Bacillus cereus — Colony-Count Technique at 30 °C", "Presumptive Bacillus cereus enumeration."],
    ["IS/ISO 8523:1991", "Microbiology — General Guidance for the Detection of Enterobacter Sakazakii (Cronobacter) in Dried Milk Products", "Detection of Cronobacter in dried milk products."],
    ["IS/ISO 17410:2019", "Microbiology of the Food Chain — Horizontal Method for the Enumeration of Psychrotrophic Microorganisms", "Enumeration of psychrotrophic microorganisms."],
    ["IS/ISO 13307:2013", "Microbiology of Food and Animal Feed — Primary Production Stage — Sampling Techniques", "Sampling techniques at the primary production stage."],
    ["IS/ISO 16140-1:2016", "Microbiology of the Food Chain — Method Validation — Part 1: Vocabulary", "Vocabulary for food microbiology method validation."],
    ["IS/ISO 16140-2:2016", "Microbiology of the Food Chain — Method Validation — Part 2: Protocol for the Validation of Alternative (Proprietary) Methods against a Reference Method", "Validation protocol for proprietary alternative methods."],
    ["IS/ISO 16140-3:2021", "Microbiology of the Food Chain — Method Validation — Part 3: Protocol for the Verification of Reference Methods and Validated Alternative Methods in a Single Laboratory", "Single-laboratory verification protocol."],
    ["IS/ISO 16140-4:2020", "Microbiology of the Food Chain — Method Validation — Part 4: Protocol for Method Validation in a Single Laboratory", "Single-laboratory method validation protocol."],
    ["IS/ISO 16140-5:2020", "Microbiology of the Food Chain — Method Validation — Part 5: Protocol for Factorial Inter-Laboratory Validation of Non-Proprietary Methods", "Inter-laboratory validation of non-proprietary methods."],
    ["IS/ISO 16140-6:2019", "Microbiology of the Food Chain — Method Validation — Part 6: Protocol for the Validation of Alternative (Proprietary) Methods for Microbiological Confirmation and Typing Procedures", "Validation of alternatives for confirmation and typing."],
  ],
};

const FOOD_CHEMISTRY: Block = {
  category: "food",
  rows: [
    ["IS/ISO 8968-2:2001", "Milk — Determination of Nitrogen Content — Part 2: Block-Digestion Method (Macro Method)", "Macro Kjeldahl nitrogen determination in milk."],
    ["IS/ISO 8968-3:2004", "Milk — Determination of Nitrogen Content — Part 3: Block-Digestion Method (Semi-Micro Rapid Routine Method)", "Rapid semi-micro nitrogen determination for milk."],
    ["IS/ISO 8968-5:2001", "Milk — Determination of Nitrogen Content — Part 5: Determination of Protein-Nitrogen Content", "Protein nitrogen content in milk and milk products."],
    ["IS/ISO 1736:2008", "Dried Milk and Dried Milk Products — Determination of Fat Content — Gravimetric Method", "Gravimetric fat determination in dried milk."],
    ["IS/ISO 1737:2008", "Evaporated Milk and Sweetened Condensed Milk — Determination of Fat Content — Gravimetric Method", "Fat determination in evaporated and condensed milk."],
    ["IS/ISO 1738:2004", "Butter — Determination of Salt Content", "Salt content determination in butter."],
    ["IS/ISO 1735:2004", "Cheese and Processed Cheese Products — Determination of Fat Content — Gravimetric Method", "Gravimetric fat determination in cheese."],
    ["IS/ISO 3432:2008", "Cheese — Determination of Fat Content — Butyrometer Method", "Butyrometer fat determination in cheese."],
    ["IS/ISO 3433:2008", "Cheese — Determination of Fat Content — Van Gulik Method", "Van Gulik fat determination for cheese."],
    ["IS/ISO 5534:2004", "Cheese and Processed Cheese — Determination of Total Solids Content", "Total solids determination in cheese."],
    ["IS/ISO 5537:2004", "Dried Milk — Determination of Moisture Content", "Moisture determination in dried milk products."],
    ["IS/ISO 6091:2010", "Dried Milk — Determination of Titratable Acidity (Reference Method)", "Reference determination of titratable acidity."],
    ["IS/ISO 6092:1980", "Dried Milk — Determination of Titratable Acidity (Routine Method)", "Routine titratable acidity determination for dried milk."],
    ["IS/ISO 8070:2007", "Milk and Milk Products — Determination of Calcium, Sodium, Potassium and Magnesium Contents — Atomic Absorption Spectrometric Method", "Mineral determination by atomic absorption spectrometry."],
    ["IS/ISO 11816-1:2013", "Milk and Milk Products — Determination of Alkaline Phosphatase Activity — Part 1: Fluorimetric Method for Milk and Milk-Based Drinks", "Fluorimetric alkaline phosphatase activity for pasteurisation control."],
    ["IS/ISO 1211:2010", "Milk — Determination of Fat Content — Gravimetric Method (Reference Method)", "Reference gravimetric fat determination for milk."],
    ["IS/ISO 2450:2008", "Cream — Determination of Fat Content — Gravimetric Method (Reference Method)", "Reference fat determination for cream."],
    ["IS/ISO 3727-1:2001", "Butter — Determination of Moisture, Non-Fat Solids and Fat Contents — Part 1: Determination of Moisture Content", "Moisture content determination in butter."],
    ["IS/ISO 3727-2:2001", "Butter — Determination of Moisture, Non-Fat Solids and Fat Contents — Part 2: Determination of Non-Fat Solids Content", "Non-fat solids determination in butter."],
    ["IS/ISO 3727-3:2003", "Butter — Determination of Moisture, Non-Fat Solids and Fat Contents — Part 3: Calculation of Fat Content", "Calculation of fat content from moisture and non-fat solids."],
    ["IS/ISO 21543:2006", "Milk Products — Guidelines for the Application of Near Infrared Spectrometry", "Near infrared spectrometry application for milk products."],
    ["IS/ISO 2173:2003", "Fruit and Vegetable Products — Determination of Soluble Solids — Refractometric Method", "Refractometric soluble solids determination."],
    ["IS/ISO 665:2020", "Oilseeds — Determination of Moisture and Volatile Matter Content", "Moisture and volatile matter in oilseeds."],
    ["IS/ISO 659:2009", "Oilseeds — Determination of Oil Content (Reference Method)", "Reference oil content determination for oilseeds."],
    ["IS/ISO 664:2008", "Oilseeds — Reduction of Laboratory Sample to Test Sample", "Laboratory sample reduction for oilseeds."],
    ["IS/ISO 729:1988", "Oilseeds — Determination of Acidity of Oils", "Acidity determination of oils extracted from oilseeds."],
    ["IS/ISO 660:2020", "Animal and Vegetable Fats and Oils — Determination of Acid Value and Acidity", "Acid value determination for fats and oils."],
    ["IS/ISO 3960:2017", "Animal and Vegetable Fats and Oils — Determination of Peroxide Value — Iodometric (Visual) Endpoint Determination", "Peroxide value determination for fats and oils."],
    ["IS/ISO 3961:2018", "Animal and Vegetable Fats and Oils — Determination of Iodine Value", "Iodine value determination for fats and oils."],
    ["IS/ISO 3657:2020", "Animal and Vegetable Fats and Oils — Determination of Saponification Value", "Saponification value determination."],
    ["IS/ISO 662:2016", "Animal and Vegetable Fats and Oils — Determination of Moisture and Volatile Matter Content", "Moisture and volatile matter in fats and oils."],
    ["IS/ISO 663:2017", "Animal and Vegetable Fats and Oils — Determination of Insoluble Impurities Content", "Insoluble impurities determination."],
    ["IS/ISO 6647-2:2020", "Rice — Determination of Amylose Content — Part 2: Routine Methods", "Routine amylose content determination in rice."],
    ["IS/ISO 6646:2011", "Rice — Determination of the Potential Milling Yield from Paddy and from Husked Rice", "Potential milling yield determination for rice."],
    ["IS/ISO 6540:2021", "Maize — Determination of Moisture Content (on Milled Grains and on Whole Grains)", "Moisture content determination for maize."],
    ["IS/ISO 6633:1984", "Fruit, Vegetables and Derived Products — Determination of Lead Content — Flameless Atomic Absorption Spectrometric Method", "Lead determination in fruit and vegetable products."],
    ["IS/ISO 6637:1984", "Fruit, Vegetables and Derived Products — Determination of Arsenic Content — Silver Diethyldithiocarbamate Spectrophotometric Method", "Arsenic determination in fruit and vegetable products."],
    ["IS/ISO 6561-1:2005", "Fruit, Vegetables and Derived Products — Determination of Cadmium Content — Part 1: Method Using Graphite Furnace Atomic Absorption Spectrometry", "Cadmium determination by graphite furnace AAS."],
    ["IS/ISO 6561-2:2005", "Fruit, Vegetables and Derived Products — Determination of Cadmium Content — Part 2: Method Using Flame Atomic Absorption Spectrometry", "Cadmium determination by flame AAS."],
    ["IS/ISO 11212-1:1997", "Starch and Derived Products — Heavy Metals Content — Part 1: Determination of Arsenic Content by Atomic Absorption Spectrometry", "Arsenic determination in starch products."],
    ["IS/ISO 11212-2:1997", "Starch and Derived Products — Heavy Metals Content — Part 2: Determination of Mercury Content by Atomic Absorption Spectrometry", "Mercury determination in starch products."],
    ["IS/ISO 11212-3:1997", "Starch and Derived Products — Heavy Metals Content — Part 3: Determination of Lead Content by Atomic Absorption Spectrometry", "Lead determination in starch products."],
    ["IS/ISO 11212-4:1997", "Starch and Derived Products — Heavy Metals Content — Part 4: Determination of Cadmium Content by Atomic Absorption Spectrometry", "Cadmium determination in starch products."],
    ["IS 1011:2019", "Biscuits — Specification", "Composition, moisture, fat and packaging requirements for biscuits.", "M", { keywords: ["biscuit", "bakery", "बिस्कुट"] }],
    ["IS 1485:2019", "Milk Powder — Specification", "Milk powder composition, solubility and microbiological limits.", "M", { keywords: ["milk powder", "दूध पाउडर"] }],
    ["IS 13690:2019", "Wheat Flour (Atta) — Specification", "Atta milling, moisture, ash and gluten requirements.", "M", { keywords: ["atta", "wheat flour", "आटा"] }],
    ["IS 1223:2019", "Iodised Salt — Specification", "Iodine content, moisture and impurity limits for edible salt.", "M", { keywords: ["salt", "iodised", "नमक"] }],
    ["IS 4906:2019", "Spices and Condiments — Turmeric, Whole and Ground — Specification", "Curcumin content, moisture and grading for turmeric."],
    ["IS 2443:2019", "Spices and Condiments — Chillies and Chilli Powder — Specification", "Capsaicin content, colour value and mould limits for chillies."],
    ["IS 3576:2019", "Spices and Condiments — Black Pepper, Whole and Ground — Specification", "Piperine content, bulk density and cleanliness for pepper."],
    ["IS 11039:2019", "Spices and Condiments — Coriander, Whole and Ground — Specification", "Volatile oil content and purity requirements for coriander."],
    ["IS 10967:2019", "Spices and Condiments — Cumin, Whole and Ground — Specification", "Volatile oil and purity requirements for cumin."],
    ["IS 1907:2019", "Spices and Condiments — Fenugreek, Whole and Ground — Specification", "Purity, volatile oil and moisture requirements for fenugreek."],
    ["IS 7348:2019", "Spices and Condiments — Mustard Seeds and Mustard Powder — Specification", "Fixed oil content and purity requirements for mustard."],
    ["IS 13286:2019", "Instant Coffee — Specification", "Instant coffee composition, moisture and cup quality requirements."],
  ],
};

const CONSUMER_PRODUCTS: Block = {
  category: "consumer",
  rows: [
    ["IS 15298-5:2010", "Footwear — Part 5: General Purpose Footwear — Specification", "General purpose footwear construction and performance requirements."],
    ["IS 15298-6:2010", "Footwear — Part 6: Sports Footwear — Specification", "Sports footwear flexing, abrasion and slip resistance."],
    ["IS 15298-7:2010", "Footwear — Part 7: Occupational Footwear — Specification", "Occupational footwear protection classes and marking."],
    ["IS 15298-8:2011", "Footwear — Part 8: Extra Protective Footwear — Specification", "Extra protective footwear with toe cap requirements."],
    ["IS 15844-4:2011", "Footwear — Part 4: Safety Footwear — Specification", "Safety footwear with penetration resistance and toe caps."],
    ["IS 15844-5:2011", "Footwear — Part 5: Test Methods for Safety Footwear", "Test methods for toe cap and penetration resistance."],
    ["IS 14407:2019", "Socks and Stockings — Specification", "Knit sock dimensions, yarn composition and colour fastness."],
    ["IS 13983:1994", "Towel Woven — Specification", "Towel absorbency, mass per unit area and dimensional stability."],
    ["IS 2566-2:2026", "Bed Sheets and Pillow Covers — Part 2: Specification", "Woven bed sheet fabric count, shrinkage and colour fastness."],
    ["IS 1943-2:2019", "Furnishing Fabrics — Part 2: Performance Requirements", "Performance requirements for upholstery and furnishing fabrics."],
    ["IS 1954-2:2019", "Textiles — Determination of Colour Fastness — Part 2: Colour Fastness to Washing", "Colour fastness to washing tests for textiles."],
    ["IS 1963-2:2019", "Textiles — Methods of Test — Part 2: Determination of Thread Density", "Thread density determination for woven fabrics."],
    ["IS 1964-2:2019", "Textiles — Methods of Test — Part 2: Determination of Mass per Unit Length and Area", "Mass per unit length and area for fabrics and yarns."],
    ["IS 1969-2:2019", "Textiles — Methods of Test — Part 2: Determination of Breaking Strength and Elongation of Fabrics", "Strip method tensile testing of fabrics."],
    ["IS 1060-2:1987", "Methods of Test for Paper and Board — Part 2: Determination of Basic Weight", "Basis weight determination for paper and board."],
    ["IS 1060-3:1987", "Methods of Test for Paper and Board — Part 3: Determination of Thickness and Apparent Bulk Density", "Thickness and bulk density measurement."],
    ["IS 1060-4:1990", "Methods of Test for Paper and Board — Part 4: Determination of Tensile Strength and Breaking Load", "Tensile strength and breaking load for paper."],
    ["IS 10037-3:1981", "Methods of Test for Paper and Paper Board — Part 3: Determination of Tearing Resistance", "Tearing resistance measurement for paper."],
    ["IS 10037-4:1986", "Methods of Test for Paper and Paper Board — Part 4: Determination of Bursting Strength", "Bursting strength of paper and board."],
    ["IS 4664:2019", "Writing and Printing Paper — Specification", "Paper grammage, brightness, opacity and strength requirements."],
    ["IS 2771-2:1990", "Paper — Specification — Part 2: Kraft Paper", "Kraft paper grades, strength and moisture requirements."],
    ["IS 6615:2019", "Paper and Board — Sampling and Conditioning", "Sampling plans and conditioning for paper testing."],
    ["IS 9915:2019", "Sleeping Bags — Specification", "Sleeping bag construction, fill weight and thermal performance."],
    ["IS 6359:2019", "Umbrellas — Specification", "Umbrella frame strength, fabric water repellency and durability."],
    ["IS 8374:2019", "Domestic Metal Furniture — Specification", "Metal furniture construction, stability and finish requirements."],
    ["IS 12480-2:2019", "Domestic Furniture — Part 2: Steel Wardrobes — Specification", "Steel wardrobe dimensions, door operation and corrosion resistance."],
    ["IS 13496-2:1992", "Domestic Water Filters — Part 2: Specification", "Domestic water filter flow rate, filtration and material safety."],
    ["IS 1757:2019", "Lead Pencils and Colour Pencils — Specification", "Pencil core strength, wood quality and toxicology limits."],
    ["IS 2106:2019", "Ink, Writing — Specification", "Writing ink colour, drying and light fastness requirements."],
    ["IS 2454-2:2019", "Textiles — Test Methods — Part 2: Determination of Abrasion Resistance", "Abrasion resistance testing of textile fabrics."],
    ["IS 13276-2:2019", "Packaging — Textile Bags for Industrial Use — Part 2: Specification", "Woven sack strength, mass and marking requirements."],
    ["IS 1381-2:2020", "Cosmetics — Shampoo — Part 2: Specification", "Shampoo quality, foaming and safety requirements."],
    ["IS 1770:2020", "Nail Polish and Nail Polish Remover — Specification", "Nail enamel drying, adhesion and solvent safety requirements."],
    ["IS 3442:2020", "Antiseptic and Disinfectant Fluids — Specification", "Phenolic coefficient, dilution and safety requirements."],
  ],
};

export const STD_WAVE23 = buildBlocks(FOOD_MICROBIOLOGY, FOOD_CHEMISTRY, CONSUMER_PRODUCTS);
