/* Extra catalogue wave 21 — chemicals, petroleum products, fertilizers,
 * paints, rubber, plastics and environmental measurement methods. These extend
 * the thinnest category in the catalogue (chemicals) with test-method series
 * that laboratories ask about, plus pipe and fitting specifications that the
 * plastics wave left uncovered. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const PETROLEUM_AND_FUELS: Block = {
  category: "chemicals",
  rows: [
    ["IS 1448-2:2019", "Methods of Test for Petroleum and Its Products — Part 2: Determination of Colour by Saybolt Chromometer", "Saybolt colour determination for light petroleum products."],
    ["IS 1448-4:2020", "Methods of Test for Petroleum and Its Products — Part 4: Determination of Density, Relative Density and API Gravity by Hydrometer", "Hydrometer determination of density and API gravity."],
    ["IS 1448-6:2018", "Methods of Test for Petroleum and Its Products — Part 6: Determination of Distillation Characteristics of Light Petroleum Products", "Distillation range determination for gasoline, kerosene and diesel."],
    ["IS 1448-8:2017", "Methods of Test for Petroleum and Its Products — Part 8: Determination of Sulphur by Bomb Method", "Total sulphur determination by bomb combustion."],
    ["IS 1448-12:2019", "Methods of Test for Petroleum and Its Products — Part 12: Determination of Copper Strip Corrosion", "Copper strip corrosion rating for fuels and solvents."],
    ["IS 1448-14:2021", "Methods of Test for Petroleum and Its Products — Part 14: Determination of Vapour Pressure (Reid Method)", "Reid vapour pressure determination for volatile products."],
    ["IS 1448-16:2018", "Methods of Test for Petroleum and Its Products — Part 16: Determination of Smoke Point of Kerosene", "Smoke point measurement for illuminating kerosene."],
    ["IS 1448-17:2019", "Methods of Test for Petroleum and Its Products — Part 17: Determination of Bromine Number and Bromine Index", "Bromine number by electrometric titration."],
    ["IS 1448-18:2018", "Methods of Test for Petroleum and Its Products — Part 18: Determination of Aniline Point", "Aniline point determination for hydrocarbon mixtures."],
    ["IS 1448-19:2020", "Methods of Test for Petroleum and Its Products — Part 19: Determination of Kinematic Viscosity", "Kinematic viscosity of transparent and opaque liquids."],
    ["IS 1448-20:2019", "Methods of Test for Petroleum and Its Products — Part 20: Determination of Water by Distillation", "Water content by distillation for petroleum products."],
    ["IS 1448-23:2018", "Methods of Test for Petroleum and Its Products — Part 23: Determination of Ash Content", "Ash determination for lubricating oils and fuels."],
    ["IS 1448-26:2020", "Methods of Test for Petroleum and Its Products — Part 26: Determination of Acidity and Neutralisation Number", "Acidity and neutralisation number for lubricants."],
    ["IS 1448-31:2019", "Methods of Test for Petroleum and Its Products — Part 31: Determination of Flash Point by Abel Apparatus", "Abel closed cup flash point for kerosene and solvents."],
    ["IS 1448-33:2021", "Methods of Test for Petroleum and Its Products — Part 33: Determination of Pour Point", "Pour point determination for lubricating oils and diesel."],
    ["IS 1448-36:2018", "Methods of Test for Petroleum and Its Products — Part 36: Determination of Total Sulphur by Ultraviolet Fluorescence", "Low-level sulphur determination by UV fluorescence."],
    ["IS 1448-39:2019", "Methods of Test for Petroleum and Its Products — Part 39: Determination of Carbon Residue (Conradson Method)", "Conradson carbon residue for fuel oils and lubricants."],
    ["IS 1448-43:2020", "Methods of Test for Petroleum and Its Products — Part 43: Determination of Octane Number by Research Method", "Research octane number determination for gasoline."],
    ["IS 1448-46:2018", "Methods of Test for Petroleum and Its Products — Part 46: Determination of Cetane Number of Diesel Fuels", "Cetane number determination using reference fuels."],
    ["IS 1448-50:2019", "Methods of Test for Petroleum and Its Products — Part 50: Determination of Water and Sediment by Centrifuge", "Water and sediment by centrifuge for fuel oils."],
    ["IS 1448-53:2021", "Methods of Test for Petroleum and Its Products — Part 53: Determination of Lubricity of Diesel Fuels", "Diesel fuel lubricity by high frequency reciprocating rig."],
    ["IS 1448-60:2018", "Methods of Test for Petroleum and Its Products — Part 60: Determination of Filterability of Diesel Fuel", "Cold filterability behaviour of diesel fuels."],
    ["IS 1448-62:2019", "Methods of Test for Petroleum and Its Products — Part 62: Determination of Oxidation Stability of Gasoline", "Induction period oxidation stability for gasoline."],
    ["IS 1448-66:2020", "Methods of Test for Petroleum and Its Products — Part 66: Determination of Vanadium and Nickel in Residual Fuels", "Trace metal determination in residual fuel oils."],
    ["IS 1448-70:2018", "Methods of Test for Petroleum and Its Products — Part 70: Determination of Base Number of Lubricating Oils", "Base number by potentiometric titration."],
    ["IS 1448-76:2019", "Methods of Test for Petroleum and Its Products — Part 76: Determination of Density and Relative Density by Digital Density Meter", "Density measurement using a digital analyser."],
    ["IS 11255-1:2020", "Methods for Measurement of Emissions from Stationary Sources — Part 1: Particulate Matter", "Isokinetic sampling and gravimetric determination of particulate matter."],
    ["IS 11255-2:2021", "Methods for Measurement of Emissions from Stationary Sources — Part 2: Sulphur Dioxide", "Sampling and determination of sulphur dioxide in stack gas."],
    ["IS 11255-3:2019", "Methods for Measurement of Emissions from Stationary Sources — Part 3: Oxides of Nitrogen", "Determination of oxides of nitrogen in flue gases."],
    ["IS 11255-4:2020", "Methods for Measurement of Emissions from Stationary Sources — Part 4: Hydrogen Sulphide and Carbon Disulphide", "Absorption and colorimetric determination of reduced sulphur compounds."],
    ["IS 11255-5:2019", "Methods for Measurement of Emissions from Stationary Sources — Part 5: Total Fluorides", "Sampling and determination of fluorides in stack emissions."],
    ["IS 11255-6:2018", "Methods for Measurement of Emissions from Stationary Sources — Part 6: Chlorine", "Determination of chlorine in stationary source emissions."],
    ["IS 11255-7:2018", "Methods for Measurement of Emissions from Stationary Sources — Part 7: Carbon Monoxide", "Non-dispersive infrared determination of carbon monoxide."],
    ["IS 11255-8:2020", "Methods for Measurement of Emissions from Stationary Sources — Part 8: Hydrogen Chloride", "Sampling and determination of hydrogen chloride in flue gas."],
    ["IS 5182-27:2019", "Methods for Measurement of Air Pollution — Part 27: Determination of Carbon Monoxide in Ambient Air", "Ambient carbon monoxide measurement by NDIR and indicator tube."],
    ["IS 5182-28:2020", "Methods for Measurement of Air Pollution — Part 28: Determination of Ozone in Ambient Air", "Ambient ozone determination by chemiluminescence and UV absorption."],
    ["IS 5182-29:2018", "Methods for Measurement of Air Pollution — Part 29: Determination of Benzo(a)Pyrene in Ambient Air", "Sampling and determination of polycyclic aromatic hydrocarbons."],
    ["IS 13824:2019", "Ambient Air Quality Monitoring Network Design — Code of Practice", "Siting, spacing and instrumentation of ambient monitoring stations."],
    ["IS 14979:2021", "Leachate Characterisation of Solid Waste — Methods of Test", "Leachate generation and analysis procedures for waste dumps."],
    ["IS 10158:2020", "Methods of Analysis of Solid Wastes — Municipal and Industrial", "Sampling and analysis of solid waste streams."],
  ],
};

const FERTILIZERS_AND_CHEMICALS: Block = {
  category: "chemicals",
  rows: [
    ["IS 6092-1:2019", "Methods of Sampling and Test for Fertilizers — Part 1: Sampling of Solid Fertilizers", "Sampling plans and sample reduction for solid fertilizers.", "M", { keywords: ["fertiliser", "sampling", "उर्वरक"] }],
    ["IS 6092-2:2019", "Methods of Sampling and Test for Fertilizers — Part 2: Determination of Moisture", "Moisture determination by oven drying and Karl Fischer methods."],
    ["IS 6092-3:2019", "Methods of Sampling and Test for Fertilizers — Part 3: Determination of Total and Ammoniacal Nitrogen", "Ammoniacal and total nitrogen determination.", "M"],
    ["IS 6092-4:2020", "Methods of Sampling and Test for Fertilizers — Part 4: Determination of Nitrate Nitrogen", "Nitrate nitrogen by devarda alloy reduction."],
    ["IS 6092-5:2018", "Methods of Sampling and Test for Fertilizers — Part 5: Determination of Total Phosphorus", "Phosphorus determination by gravimetric and spectrophotometric methods.", "M"],
    ["IS 6092-6:2019", "Methods of Sampling and Test for Fertilizers — Part 6: Determination of Water-Soluble Phosphorus", "Water-soluble phosphorus fraction in phosphatic fertilizers."],
    ["IS 6092-7:2018", "Methods of Sampling and Test for Fertilizers — Part 7: Determination of Potassium", "Potassium determination by flame photometry and gravimetric tetraphenylborate."],
    ["IS 6092-8:2020", "Methods of Sampling and Test for Fertilizers — Part 8: Determination of Sulphur", "Total sulphur in fertilizers and soil amendments."],
    ["IS 6092-9:2019", "Methods of Sampling and Test for Fertilizers — Part 9: Determination of Micronutrients", "Zinc, copper, iron and manganese determination by atomic absorption."],
    ["IS 6092-10:2021", "Methods of Sampling and Test for Fertilizers — Part 10: Determination of Chloride", "Chloride determination by titration and ion chromatography."],
    ["IS 6092-11:2020", "Methods of Sampling and Test for Fertilizers — Part 11: Determination of Particle Size", "Sieve analysis and granularity requirements for fertilizers."],
    ["IS 6092-12:2019", "Methods of Sampling and Test for Fertilizers — Part 12: Determination of Biuret in Urea", "Biuret content determination for urea fertilizers."],
    ["IS 260:2019", "Aluminium Sulphate for Water Treatment — Specification", "Alum grades, alumina content and impurity limits for potable water.", "M"],
    ["IS 2724:2018", "Sodium Aluminate for Water Treatment — Specification", "Sodium aluminate composition for coagulation in water treatment."],
    ["IS 7322:2020", "Lime for Water Treatment — Specification", "Hydrated and quick lime requirements for water and waste water treatment."],
    ["IS 10553-1:2019", "Polyaluminium Chloride for Water Treatment — Part 1: Specification", "PAC composition, basicity and effectiveness requirements."],
    ["IS 15573:2019", "Bleaching Powder (Calcium Hypochlorite) — Specification", "Available chlorine content, stability and packing requirements."],
    ["IS 101-13:2019", "Methods of Sampling and Test for Ready Mixed Paints — Part 13: Determination of Spreading Rate", "Spreading rate determination on standard panels."],
    ["IS 101-14:2019", "Methods of Sampling and Test for Ready Mixed Paints — Part 14: Determination of Water Resistance", "Water resistance of dried paint films."],
    ["IS 101-15:2020", "Methods of Sampling and Test for Ready Mixed Paints — Part 15: Determination of Resistance to Salt Spray", "Accelerated salt spray resistance testing."],
    ["IS 101-16:2019", "Methods of Sampling and Test for Ready Mixed Paints — Part 16: Determination of Resistance to Humidity", "Humidity cabinet testing of coatings."],
    ["IS 101-17:2019", "Methods of Sampling and Test for Ready Mixed Paints — Part 17: Determination of Resistance to Heat", "Heat resistance behaviour of paint films."],
    ["IS 101-18:2020", "Methods of Sampling and Test for Ready Mixed Paints — Part 18: Determination of Washability and Scrub Resistance", "Scrub resistance and washability of coatings."],
    ["IS 101-19:2019", "Methods of Sampling and Test for Ready Mixed Paints — Part 19: Determination of Drying Time", "Surface dry, hard dry and tack-free time determination."],
    ["IS 101-20:2020", "Methods of Sampling and Test for Ready Mixed Paints — Part 20: Determination of Wet and Dry Film Thickness", "Film thickness measurement by gauge and microscope."],
    ["IS 164:2021", "Ready Mixed Paint, Brushing, Road Marking, White and Yellow — Specification", "Road marking paint composition, drying and retro-reflectivity support.", "V", { keywords: ["road marking", "paint", "road safety"] }],
    ["IS 168:2019", "Ready Mixed Paint, Brushing, Aluminium — Specification", "Aluminium paint composition and heat resistance requirements."],
    ["IS 337:2020", "Varnish, Finishing, for General Purposes — Specification", "Varnish composition, drying time and film flexibility."],
    ["IS 367:2019", "Linseed Oil, Raw and Refined, for Paints — Specification", "Linseed oil acid value, iodine value and drying behaviour."],
    ["IS 866:2018", "Zinc Chrome, Priming, for Paints — Specification", "Zinc chrome primer composition and corrosion performance."],
    ["IS 1327:2019", "Bituminous Black Paint for General Purposes — Specification", "Bituminous paint composition, drying and water resistance."],
    ["IS 427:2019", "Distemper, Dry, Powder Form — Specification", "Dry distemper composition, opacity and adhesion requirements."],
    ["IS 2395-2:2019", "Plastic Emulsion Paints — Part 2: Test Methods", "Test methods for interior and exterior emulsion paints."],
    ["IS 2932-2:2019", "Enamel, Synthetic, Exterior — Part 2: Test Methods", "Test methods for exterior synthetic enamel."],
    ["IS 517:2019", "Acetone, Technical — Specification", "Acetone purity, water content and distillation range."],
    ["IS 529:2020", "Toluene, Technical — Specification", "Toluene purity, colour and sulphur content limits."],
    ["IS 1473:2019", "Xylene, Technical — Specification", "Xylene isomer content, purity and distillation range."],
    ["IS 2830:2019", "Methanol, Technical — Specification", "Methanol purity, water and permanganate time requirements."],
    ["IS 8543:2019", "Sodium Lauryl Sulphate, Technical — Specification", "Active matter content and unsulphated matter limits."],
    ["IS 4955:2020", "Synthetic Detergents for Household Use — Specification", "Detergent formulation performance, foam and safety requirements."],
    ["IS 285:2019", "Laundry Soap — Specification", "Total fatty matter, free alkali and moisture limits for laundry soap."],
    ["IS 288:2019", "Soap for Toilet Use — Specification", "Toilet soap composition, colour and free caustic alkali limits."],
    ["IS 4662:2019", "Glycerine (Glycerol) — Specification", "Glycerine grades, purity and chloride limits."],
    ["IS 8846:2019", "Pesticides — Sampling of Technical Grade Materials", "Sampling procedure and sample size for technical grade pesticides."],
    ["IS 8190-1:2019", "Pesticides — Specification for Technical Grade Insecticides — Part 1: Organochlorine Insecticides", "Technical grade organochlorine insecticide purity requirements."],
  ],
};

const RUBBER_AND_PLASTICS: Block = {
  category: "plastics",
  rows: [
    ["IS 3400-23:1977", "Methods of Test for Vulcanized Rubbers — Part 23: Determination of Compression Set at Elevated Temperatures", "Compression set testing under elevated and low temperature."],
    ["IS 3400-24:1977", "Methods of Test for Vulcanized Rubbers — Part 24: Determination of Tear Strength", "Tear strength determination for vulcanized rubber."],
    ["IS 3400-25:1977", "Methods of Test for Vulcanized Rubbers — Part 25: Determination of Rebound Resilience", "Rebound resilience using vertical and rotary apparatus."],
    ["IS 3400-26:1978", "Methods of Test for Vulcanized Rubbers — Part 26: Determination of Abrasion Resistance", "Abrasion resistance using a rotating drum apparatus."],
    ["IS 3400-27:1978", "Methods of Test for Vulcanized Rubbers — Part 27: Determination of Crack Growth", "Crack growth measurement under repeated flexing."],
    ["IS 3400-28:1978", "Methods of Test for Vulcanized Rubbers — Part 28: Determination of Adhesion to Fabric", "Rubber-to-fabric adhesion strength testing."],
    ["IS 13360-5-3:1996", "Plastics — Methods of Testing — Part 5-3: Mechanical Properties — Determination of Flexural Properties", "Flexural modulus and strength of rigid plastics."],
    ["IS 13360-5-6:1996", "Plastics — Methods of Testing — Part 5-6: Mechanical Properties — Determination of Impact Strength by Charpy Method", "Charpy impact strength determination."],
    ["IS 13360-5-8:2005", "Plastics — Methods of Testing — Part 5-8: Mechanical Properties — Determination of Hardness by Rockwell and Durometer", "Rockwell and durometer hardness for plastics."],
    ["IS 13360-6-3:1996", "Plastics — Methods of Testing — Part 6-3: Thermal Properties — Determination of Softening Range", "Softening range determination for thermoplastics."],
    ["IS 13360-6-4:1996", "Plastics — Methods of Testing — Part 6-4: Thermal Properties — Determination of Melting Temperature", "Melting temperature determination by capillary and DSC methods."],
    ["IS 13360-6-5:1996", "Plastics — Methods of Testing — Part 6-5: Thermal Properties — Determination of Thermal Conductivity", "Thermal conductivity measurement for plastics."],
    ["IS 13360-6-6:1996", "Plastics — Methods of Testing — Part 6-6: Thermal Properties — Determination of Coefficient of Linear Thermal Expansion", "Linear thermal expansion coefficient of plastic materials."],
    ["IS 13360-6-7:2002", "Plastics — Methods of Testing — Part 6-7: Thermal Properties — Determination of Brittleness Temperature", "Brittleness temperature determination for films and sheets."],
    ["IS 13360-6-8:1997", "Plastics — Methods of Testing — Part 6-8: Thermal Properties — Determination of Heat Deflection Temperature", "Heat deflection temperature under load."],
    ["IS 13360-6-9:1997", "Plastics — Methods of Testing — Part 6-9: Thermal Properties — Determination of Vicat Softening Temperature", "Vicat softening temperature of thermoplastics."],
    ["IS 13360-6-10:1997", "Plastics — Methods of Testing — Part 6-10: Thermal Properties — Determination of Flammability", "Flammability rating by horizontal and vertical burning tests."],
    ["IS 13360-6-12:2000", "Plastics — Methods of Testing — Part 6-12: Thermal Properties — Determination of Smoke Density", "Smoke density testing under flaming conditions."],
    ["IS 13360-6-13:2000", "Plastics — Methods of Testing — Part 6-13: Thermal Properties — Determination of Oxygen Index", "Limiting oxygen index determination."],
    ["IS 13360-7-2:1996", "Plastics — Methods of Testing — Part 7-2: Optical Properties — Determination of Haze and Luminous Transmittance", "Haze and light transmission measurement for films."],
    ["IS 13360-8-2:1996", "Plastics — Methods of Testing — Part 8-2: Electrical Properties — Determination of Volume and Surface Resistivity", "Volume and surface resistivity of plastics."],
    ["IS 13360-8-3:1996", "Plastics — Methods of Testing — Part 8-3: Electrical Properties — Determination of Dielectric Strength", "Dielectric breakdown strength testing."],
    ["IS 13360-8-4:1996", "Plastics — Methods of Testing — Part 8-4: Electrical Properties — Determination of Dielectric Constant and Dissipation Factor", "Dielectric constant and loss measurements."],
    ["IS 13360-8-5:1994", "Plastics — Methods of Testing — Part 8-5: Electrical Properties — Determination of Insulation Resistance", "Insulation resistance of plastic components."],
    ["IS 13360-8-7:1997", "Plastics — Methods of Testing — Part 8-7: Electrical Properties — Determination of Resistance to Tracking", "Comparative tracking index for plastic materials."],
    ["IS 13360-8-8:1997", "Plastics — Methods of Testing — Part 8-8: Electrical Properties — Determination of Arc Resistance", "Arc resistance of insulation materials."],
    ["IS 13360-8-9:1997", "Plastics — Methods of Testing — Part 8-9: Electrical Properties — Determination of Relative Permittivity", "Relative permittivity for cable insulation compounds."],
    ["IS 13360-8-10:2001", "Plastics — Methods of Testing — Part 8-10: Electrical Properties — Determination of Electrical Strength of Thin Films", "Dielectric strength of thin plastic films."],
    ["IS 13360-8-12:2001", "Plastics — Methods of Testing — Part 8-12: Electrical Properties — Determination of Resistance to Electrolytic Corrosion", "Electrolytic corrosion resistance evaluation."],
    ["IS 13360-21-1:1996", "Plastics — Methods of Testing — Part 21-1: Determination of Water Absorption", "Water absorption of moulded plastics."],
    ["IS 13360-21-2:1996", "Plastics — Methods of Testing — Part 21-2: Determination of Moisture Content", "Moisture content of plastic moulding compounds."],
    ["IS 13360-22-1:1996", "Plastics — Methods of Testing — Part 22-1: Determination of Density and Specific Gravity", "Density and specific gravity by displacement and pyknometer."],
    ["IS 13360-23-1:2018", "Plastics — Methods of Testing — Part 23-1: Determination of Environmental Stress Cracking", "Environmental stress crack resistance testing."],
    ["IS 12786:2018", "High Density Polyethylene (HDPE) Pipes for Sewerage and Industrial Effluents — Specification", "HDPE pipes for effluent and sewer duty, with stiffness classes."],
    ["IS 12818:2010", "Unplasticized PVC Pipes for Soil, Waste and Vent Applications — Specification", "SWR pipe and fitting dimensions and impact performance."],
    ["IS 12701:2019", "Rotational Moulded Polyethylene Water Storage Tanks — Specification", "Tank material, wall thickness and impact requirements."],
    ["IS 7634-2:2003", "Unplasticized PVC Pipes for Potable Water Supplies — Part 2: Fittings — Specification", "UPVC fittings for potable water pipelines."],
    ["IS 7634-3:2003", "Unplasticized PVC Pipes for Potable Water Supplies — Part 3: Solvent Cements — Specification", "Solvent cement composition and joint strength requirements."],
    ["IS 10840:2019", "Chlorinated Polyvinyl Chloride (CPVC) Pipes and Fittings for Hot and Cold Water — Specification", "CPVC pipe, fitting and joint requirements for plumbing systems."],
    ["IS 14735:2000", "Unplasticized PVC Pipes for Drainage and Sewerage — Specification", "UPVC drainage pipe sizes and stiffness requirements."],
    ["IS 15497:2004", "Polyethylene Pipes for the Conveyance of Water — Specification", "MDPE and HDPE pipe requirements for water conveyance."],
    ["IS 15328:2003", "Unplasticized PVC Foam-Core Pipes and Fittings for Soil, Waste and Vent Systems — Specification", "Foam core SWR pipe construction and performance."],
  ],
};

export const STD_WAVE21 = buildBlocks(
  PETROLEUM_AND_FUELS,
  FERTILIZERS_AND_CHEMICALS,
  RUBBER_AND_PLASTICS,
);
