/* Extra catalogue wave 20 — mechanical engineering: fastener and thread
 * standards, cast and wrought steel products, pipe and tube specifications,
 * pumps and valves, lifting and hoisting equipment, gas appliances,
 * fire-fighting equipment and automotive functional-safety adoptions. */
import { buildBlocks, type Block } from "@/db/seed-kit";

const FASTENERS_AND_THREADS: Block = {
  category: "mechanical",
  rows: [
    ["IS 1367-2:1979", "Technical Supply Conditions for Threaded Steel Fasteners — Part 2: Tolerances for Fasteners", "Dimensional tolerances for threaded steel fasteners."],
    ["IS 1367-4:1995", "Technical Supply Conditions for Threaded Steel Fasteners — Part 4: Acceptance Inspection", "Acceptance inspection and sampling of fastener lots."],
    ["IS 1367-7:1980", "Technical Supply Conditions for Threaded Steel Fasteners — Part 7: Hardness Test", "Hardness testing of threaded fasteners."],
    ["IS 1367-8:1981", "Technical Supply Conditions for Threaded Steel Fasteners — Part 8: Tensile Test", "Tensile testing of bolts, screws and studs."],
    ["IS 1367-9:1979", "Technical Supply Conditions for Threaded Steel Fasteners — Part 9: Impact Test", "Impact testing of fastener material."],
    ["IS 1367-12:1979", "Technical Supply Conditions for Threaded Steel Fasteners — Part 12: Torsional Test", "Torsional strength testing of fasteners."],
    ["IS 1367-15:1987", "Technical Supply Conditions for Threaded Steel Fasteners — Part 15: Marking and Packaging", "Marking, identification and packaging of fasteners."],
    ["IS 1367-18:1987", "Technical Supply Conditions for Threaded Steel Fasteners — Part 18: Test Methods for Locking Fasteners", "Test methods for prevailing torque and locking fasteners."],
    ["IS 1367-19:1990", "Technical Supply Conditions for Threaded Steel Fasteners — Part 19: Weld Studs", "Requirements for welded studs."],
    ["IS 1367-20:1995", "Technical Supply Conditions for Threaded Steel Fasteners — Part 20: Threaded Steel Fasteners for Use in Corrosive Environments", "Fastener selection and protection for corrosive service."],
    ["IS 1367-21:2002", "Technical Supply Conditions for Threaded Steel Fasteners — Part 21: Bolts, Screws, Studs and Nuts for High-Temperature Service", "Fasteners for high-temperature bolted joints."],
    ["IS 1367-22:2005", "Technical Supply Conditions for Threaded Steel Fasteners — Part 22: Fasteners for Low-Temperature Service", "Fastener requirements for low-temperature service."],
    ["IS 1363-4:2002", "ISO Metric Screw Threads — Part 4: Screw Threads for Fasteners — Tolerances and Limits of Size", "Limits of size for metric fastener threads."],
    ["IS 1363-5:2002", "ISO Metric Screw Threads — Part 5: Screw Threads for Threaded Steel Fasteners — Designation and Gauging", "Designation and gauging of metric threads."],
    ["IS 1363-6:2002", "ISO Metric Screw Threads — Part 6: Screw Threads for Coarse and Fine Pitches — Selection", "Selection of coarse and fine thread pitches."],
    ["IS 1364-3:2002", "Hexagon Head Bolts, Screws and Nuts of Product Grades A, B and C — Part 3: Hexagon Head Screws and Nuts — Dimensions", "Dimensions for hexagon head screws and nuts."],
    ["IS 1364-4:2002", "Hexagon Head Bolts, Screws and Nuts of Product Grades A, B and C — Part 4: Hexagon Socket Head Cap Screws — Dimensions", "Socket head cap screw dimensions."],
    ["IS 1364-5:2002", "Hexagon Head Bolts, Screws and Nuts of Product Grades A, B and C — Part 5: Hexagon Flange Bolts and Nuts — Dimensions", "Flange bolt and nut dimensions."],
    ["IS 1364-6:2002", "Hexagon Head Bolts, Screws and Nuts of Product Grades A, B and C — Part 6: Hexagon Nuts with Fine Pitch Thread — Dimensions", "Fine pitch hexagon nut dimensions."],
    ["IS 4218-3:2023", "ISO Metric Hexagon Bolts, Screws and Nuts — Part 3: Hexagon Bolts and Screws with Reduced Shank — Dimensions", "Reduced shank bolt and screw dimensions."],
    ["IS 4218-4:2023", "ISO Metric Hexagon Bolts, Screws and Nuts — Part 4: Hexagon Nuts with Metric Fine Pitch Thread — Dimensions", "Metric fine pitch hexagon nut dimensions."],
    ["IS 4218-6:2023", "ISO Metric Hexagon Bolts, Screws and Nuts — Part 6: Hexagon Head Bolts and Screws with Threaded Length — Dimensions", "Threaded length variants for hexagon bolts and screws."],
    ["IS 4218-8:2023", "ISO Metric Hexagon Bolts, Screws and Nuts — Part 8: Hexagon Socket Set Screws — Dimensions", "Hexagon socket set screw dimensions."],
    ["IS 6640-2:1972", "Plain Washers — Part 2: Specification for Plain Washers for General Engineering Purposes", "Plain washer dimensions, material and finish."],
    ["IS 2016:1967", "Plain Washers — Specification", "Washer thickness, hardness and surface finish requirements."],
    ["IS 2614:2022", "Spring Washers — Specification", "Spring washer types, load-deflection and hardness requirements."],
    ["IS 4799:1999", "Spring Lock Washers for General Engineering Purposes — Specification", "Spring lock washer dimensions and mechanical requirements."],
  ],
};

const STEEL_AND_CASTINGS: Block = {
  category: "mechanical",
  rows: [
    ["IS 1570-3:2018", "Alloy Steel for General Engineering Purposes — Part 3: Chromium-Molybdenum Steels — Specification", "Cr-Mo grades for elevated temperature and pressure service."],
    ["IS 1570-4:2018", "Alloy Steel for General Engineering Purposes — Part 4: Nickel-Chromium Steels — Specification", "Ni-Cr grades for high-strength engineering applications."],
    ["IS 1570-5:2018", "Alloy Steel for General Engineering Purposes — Part 5: Boron and Manganese Steels — Specification", "Through-hardening grades for shafts and gears."],
    ["IS 1570-6:2018", "Alloy Steel for General Engineering Purposes — Part 6: Stainless and Heat-Resisting Steels — Specification", "Corrosion and heat-resisting grades for engineering use."],
    ["IS 1570-7:2018", "Alloy Steel for General Engineering Purposes — Part 7: Tool and Die Steels — Specification", "Tool and die steel grades and heat treatment requirements."],
    ["IS 1570-8:2018", "Alloy Steel for General Engineering Purposes — Part 8: Spring Steels — Specification", "Alloy spring steel grades and cleanliness requirements."],
    ["IS 513-3:2016", "Cold Reduced Carbon Steel Sheet and Strip — Part 3: Drawing and Deep Drawing Qualities", "Formability grades for drawing and deep drawing."],
    ["IS 513-4:2016", "Cold Reduced Carbon Steel Sheet and Strip — Part 4: Structural Qualities", "Cold reduced sheet for structural applications."],
    ["IS 513-5:2016", "Cold Reduced Carbon Steel Sheet and Strip — Part 5: High Tensile Qualities", "High strength cold reduced sheet grades."],
    ["IS 1865:1991", "Iron Castings with Spheroidal or Nodular Graphite — Specification", "SG iron grades with property requirements by casting thickness."],
    ["IS 2027:2000", "Steel Castings for General Engineering Purposes — Specification", "Carbon and low-alloy steel casting grades and test requirements."],
    ["IS 7507:2022", "Fusion Welded Structural Steel Pipes for Pressure Service — Specification", "Welded pipe grades for pressure piping and boilers."],
    ["IS 4712:2018", "Electric Resistance Welded Steel Pipes for Structural Applications — Specification", "ERW pipe dimensions, grade and weld integrity requirements."],
    ["IS 9295:2020", "Steel Tubes for Structural Purposes — Specification", "Hollow section and tube requirements for structural work."],
    ["IS 4454-3:1975", "Spring Steel Wire — Part 3: Oil Hardened and Tempered Wire — Specification", "Oil hardened and tempered spring wire grades."],
    ["IS 6526:2020", "Steel Forgings for Gears and Gear Shafts — Specification", "Forged gear blank quality and hardenability requirements."],
  ],
};

const PUMPS_VALVES_AND_MACHINERY: Block = {
  category: "mechanical",
  rows: [
    ["IS 2906:2020", "Sluice Valves for Water Works Purposes — Specification", "Sluice valve construction, pressure rating and test requirements."],
    ["IS 1703:2018", "Bronze Gate Valves for Water Works — Specification", "Bronze gate valve dimensions and hydrostatic test requirements."],
    ["IS 4038:2021", "Foot Valves for Water Works — Specification", "Foot valve construction, leakage and strength requirements."],
    ["IS 8034:2019", "Submersible Pump Sets — Specification", "Submersible pump set performance, construction and test requirements."],
    ["IS 10981:2019", "Vertical Turbine Pumps — Specification", "Vertical turbine pump hydraulic and mechanical requirements."],
    ["IS 6595-1:2016", "Horizontal Centrifugal Pumps — Part 1: General Requirements", "General engineering requirements for centrifugal pumps."],
    ["IS 6595-2:2016", "Horizontal Centrifugal Pumps — Part 2: Test Methods", "Performance testing of centrifugal pumps."],
    ["IS 15887:2019", "Energy Efficiency of Rotodynamic Pumps — Test Methods and Classification", "Efficiency classification and test methods for pumps."],
    ["IS 9021:2021", "Butterfly Valves for General Purposes — Specification", "Butterfly valve design, sealing and pressure test requirements."],
    ["IS 14878:2000", "Valves for Liquefied Petroleum Gas Cylinders — Specification", "LPG cylinder valve construction and leak-tightness requirements."],
    ["IS 14665-2:2000", "Code of Practice for Installation and Maintenance of Electric Lifts — Part 2: Car Requirements", "Car construction, dimensions and enclosure requirements for lifts."],
    ["IS 14665-3:2000", "Code of Practice for Installation and Maintenance of Electric Lifts — Part 3: Safety Requirements", "Safety devices for electric lifts and their maintenance."],
    ["IS 14665-5:2000", "Code of Practice for Installation and Maintenance of Electric Lifts — Part 5: Suspension Ropes, Compensation Ropes and Governor Ropes", "Rope selection, termination and inspection for lifts."],
    ["IS 14665-6:2000", "Code of Practice for Installation and Maintenance of Electric Lifts — Part 6: Guide Rails, Buffers and Safety Gear", "Guide rail alignment, buffer and safety gear requirements."],
    ["IS 15785:2008", "Escalators and Moving Walks — Safety Requirements", "Escalator and moving walk safety, braking and inspection requirements."],
    ["IS 13834-2:1993", "Cranes — Competency Requirements for Operators and Riggers — Part 2: Mobile Cranes", "Operator competency requirements for mobile cranes."],
    ["IS 13834-3:1993", "Cranes — Competency Requirements for Operators and Riggers — Part 3: Tower Cranes", "Operator competency requirements for tower cranes."],
    ["IS 13834-4:1993", "Cranes — Competency Requirements for Operators and Riggers — Part 4: Overhead Travelling Cranes", "Operator competency requirements for overhead travelling cranes."],
    ["IS 15369:2019", "Chain Slings for Lifting Purposes — Specification", "Grade 80 and 100 chain sling requirements and proof testing."],
    ["IS 3972-1:2020", "Hoisting Ropes and Slings — Part 1: Wire Rope Slings — Specification", "Wire rope sling construction and safe working load marking."],
    ["IS 9716:2021", "Textile Slings for General Purpose — Specification", "Webbing sling materials, strength and marking requirements."],
    ["IS 3600-2:1985", "Methods of Testing Fusion Welded Joints — Part 2: Radiographic Examination", "Radiographic examination of fusion welded joints."],
    ["IS 3600-3:1985", "Methods of Testing Fusion Welded Joints — Part 3: Ultrasonic Examination", "Ultrasonic examination of welded joints."],
    ["IS 3600-4:1985", "Methods of Testing Fusion Welded Joints — Part 4: Magnetic Particle Examination", "Magnetic particle examination of weldments."],
    ["IS 13927:2019", "Welding Consumables — Covered Electrodes for Manual Metal Arc Welding of Stainless Steels", "Electrode classification and deposit composition for stainless steels."],
    ["IS 1181-1:2021", "Welding Consumables — Covered Electrodes for Manual Metal Arc Welding of Carbon and Carbon-Manganese Steels — Part 1: Classification and Requirements", "Electrode classification, mechanical properties and recovery."],
    ["IS 1181-2:2021", "Welding Consumables — Covered Electrodes for Manual Metal Arc Welding of Carbon and Carbon-Manganese Steels — Part 2: Test Methods", "Test methods for all-weld-metal and deposited metal tensile tests."],
    ["IS 6560:2000", "Filler Rods and Wires for Gas Tungsten Arc Welding — Specification", "TIG filler rod classification for carbon and stainless steels."],
    ["IS 2320:2018", "Gas Welding Rods for Copper and Copper Alloys — Specification", "Filler rod composition for copper and copper alloy welding."],
    ["IS 2546:1974", "Fire Extinguishers — Portable Water Type and Foam Type — Specification", "Extinguisher body strength, capacity and discharge requirements.", "M", { related: ["IS 15683:2018"] }],
    ["IS 15368:2019", "Fire Hose Boxes for Buildings — Specification", "Hose box construction and installation requirements."],
    ["IS 4927:2019", "Fire Hose Coupling, Branch Pipe and Nozzles — Specification", "Coupling, branch pipe and nozzle dimensions and pressures."],
    ["IS 15493:2015", "Gaseous Fire Extinguishing Systems — Design, Installation and Maintenance", "Design and maintenance of clean agent extinguishing systems."],
    ["IS 2825-2:2021", "Code for Unfired Pressure Vessels — Part 2: Materials for Pressure Vessels", "Permitted materials and evidence of strength for pressure parts."],
    ["IS 2825-3:2021", "Code for Unfired Pressure Vessels — Part 3: Design of Pressure Vessels", "Design rules for shells, heads and nozzle reinforcement."],
    ["IS 4503-2:2019", "Code for Shell and Tube Heat Exchangers — Part 2: Mechanical Design", "Tube sheet, baffle and flange design for shell and tube exchangers."],
    ["IS 3196-3:2021", "Welded Steel Cylinders for Liquefied Petroleum Gas — Part 3: Cylinders for Automobile Application — Specification", "Automotive LPG cylinder construction and test requirements."],
    ["IS 7285-3:2018", "Refillable Seamless Steel Cylinders for Compressed Gas — Part 3: Cylinders for Medical Gas Service", "Medical oxygen and nitrous oxide cylinder requirements."],
    ["IS 9345:2020", "LPG Pressure Regulators for Domestic Use — Specification", "Domestic LPG regulator flow rate, lock-up and safety requirements."],
    ["IS 4246:2021", "Domestic Cooking Gas Stoves — Specification", "Burner performance, thermal efficiency and safety requirements.", "V", { keywords: ["gas stove", "lpg", "चूल्हा"] }],
    ["IS 2974:2018", "Domestic Kerosene Pressure Stoves and Burners — Specification", "Kerosene pressure stove performance and safety requirements."],
    ["IS 11058:2020", "Electric Chain Hoists — Specification", "Electric chain hoist rating, braking and test requirements."],
    ["IS 5603:2019", "Electrical Wire Rope Hoists — Specification", "Wire rope hoist construction, duty class and testing."],
    ["IS 10403:1989", "Industrial Trucks — Fork Lift Trucks — Specification", "Fork lift truck capacity rating and stability requirements."],
    ["IS 13656:2000", "Hydraulic Scissor Lifts — Specification", "Scissor lift platform strength and safety device requirements."],
    ["IS 9417:1989", "Woodworking Bandsaws — Specification", "Bandsaw dimensions, guarding and accuracy requirements."],
    ["IS 8114:1987", "Hydraulic Presses for Plastics and Metal Working — Specification", "Press frame strength, control and safety requirements."],
    ["IS 5151:2020", "Hand Hammers — Specification", "Hammer head mass, hardness and handle fixing requirements."],
    ["IS 2028:2021", "Double Enders and Ring Spanners — Specification", "Spanner jaw dimensions, torque capacity and marking."],
    ["IS 3914:2019", "Engineering Files and Rasps — Specification", "File cut, length and hardness requirements."],
    ["IS 1841:2019", "Wood Screws — Specification", "Wood screw dimensions, thread form and material."],
  ],
};

const AUTOMOTIVE_AND_SYSTEMS: Block = {
  category: "mechanical",
  rows: [
    ["IS/ISO 26262-1:2018", "Road Vehicles — Functional Safety — Part 1: Vocabulary", "Vocabulary used across the automotive functional safety series."],
    ["IS/ISO 26262-2:2018", "Road Vehicles — Functional Safety — Part 2: Management of Functional Safety", "Functional safety management during development and production."],
    ["IS/ISO 26262-3:2018", "Road Vehicles — Functional Safety — Part 3: Concept Phase", "Item definition, hazard analysis and functional safety concept."],
    ["IS/ISO 26262-4:2018", "Road Vehicles — Functional Safety — Part 4: Product Development at the System Level", "System-level functional safety requirements and testing."],
    ["IS/ISO 26262-5:2018", "Road Vehicles — Functional Safety — Part 5: Product Development at the Hardware Level", "Hardware design, metrics and diagnostic coverage requirements."],
    ["IS/ISO 26262-6:2018", "Road Vehicles — Functional Safety — Part 6: Product Development at the Software Level", "Software safety requirements, architecture and verification."],
    ["IS/ISO 26262-7:2018", "Road Vehicles — Functional Safety — Part 7: Production, Operation, Service and Decommissioning", "Safety during production, operation, service and decommissioning."],
    ["IS/ISO 26262-8:2018", "Road Vehicles — Functional Safety — Part 8: Supporting Processes", "Supporting processes including change management and documentation."],
    ["IS/ISO 26262-9:2018", "Road Vehicles — Functional Safety — Part 9: Automotive Safety Integrity Level (ASIL)-Oriented and Safety-Oriented Analyses", "ASIL decomposition and safety analysis methods."],
    ["IS/ISO 26262-10:2018", "Road Vehicles — Functional Safety — Part 10: Guidelines on ISO 26262", "Explanatory guidelines for applying the functional safety series."],
    ["IS/ISO 26262-11:2018", "Road Vehicles — Functional Safety — Part 11: Guidelines on Application of ISO 26262 to Semiconductors", "Applying functional safety requirements to semiconductor development."],
    ["IS/ISO 26262-12:2018", "Road Vehicles — Functional Safety — Part 12: Adaptation of ISO 26262 for Motorcycles", "Functional safety adaptation for motorcycle applications."],
    ["IS/ISO 6469-1:2019", "Electrically Propelled Road Vehicles — Safety Specifications — Part 1: Rechargeable Energy Storage System (RESS)", "Safety of rechargeable energy storage systems in electric vehicles."],
    ["IS/ISO 6469-2:2019", "Electrically Propelled Road Vehicles — Safety Specifications — Part 2: Vehicle Operational Safety", "Operational safety of electrically propelled vehicles."],
    ["IS/ISO 6469-3:2021", "Electrically Propelled Road Vehicles — Safety Specifications — Part 3: Electrical Safety", "Protection of persons against electric shock in electric vehicles."],
    ["IS/ISO 15118-1:2019", "Road Vehicles — Vehicle to Grid Communication Interface — Part 1: General Information and Use-Case Definition", "Use cases and general requirements for vehicle-to-grid communication."],
    ["IS/ISO 15118-2:2014", "Road Vehicles — Vehicle-to-Grid Communication Interface — Part 2: Network and Application Protocol Requirements", "Protocol requirements for conductive charging communication."],
    ["IS/ISO 15118-3:2015", "Road Vehicles — Vehicle to Grid Communication Interface — Part 3: Physical and Data Link Layer Requirements", "Physical and data link layer requirements for EV communication."],
    ["IS 11852-2:2019", "Automotive Vehicles — Lighting and Light Signalling Devices — Part 2: Head Lamps with Filament Lamps — Specification", "Filament head lamp photometric and endurance requirements."],
    ["IS 11852-3:2019", "Automotive Vehicles — Lighting and Light Signalling Devices — Part 3: Direction Indicators — Specification", "Direction indicator photometric and switching requirements."],
    ["IS 11852-4:2019", "Automotive Vehicles — Lighting and Light Signalling Devices — Part 4: Stop Lamps and Tail Lamps — Specification", "Stop and tail lamp requirements for motor vehicles."],
    ["IS 11852-5:2019", "Automotive Vehicles — Lighting and Light Signalling Devices — Part 5: Rear Registration Plate Illuminating Devices — Specification", "Rear number plate lamp requirements."],
    ["IS 16365:2015", "Automotive Vehicles — Electric Horns — Specification", "Horn sound pressure level, endurance and current draw requirements."],
    ["IS 15786:2019", "Automotive Vehicles — Air Filters for Internal Combustion Engines — Specification", "Filter efficiency, pressure drop and burst requirements."],
    ["IS 16061:2019", "Automotive Vehicles — Clutch Assemblies — Specification", "Clutch facing strength, torque capacity and durability."],
    ["IS 11898:2018", "Automotive Vehicles — Brake Fluid — Specification", "Brake fluid boiling point, viscosity and compatibility requirements."],
    ["IS 13750:2020", "Automotive Vehicles — Wheel Rims for Two and Three Wheelers — Specification", "Rim dimensions, runout and load capacity requirements."],
    ["IS 15129:2019", "Automotive Vehicles — Leaf Springs — Specification", "Leaf spring material, camber and fatigue requirements."],
  ],
};

export const STD_WAVE20 = buildBlocks(
  FASTENERS_AND_THREADS,
  STEEL_AND_CASTINGS,
  PUMPS_VALVES_AND_MACHINERY,
  AUTOMOTIVE_AND_SYSTEMS,
);
